import type { ActivityMethod } from "@/lib/activity-methods";

/** AFK / listed wiki tables from Pay-to-play Fishing training. Not 3-tick. */
export const FISHING_RATE_TABLES: ActivityMethod[] = [
  {
    id: "fly-fishing-afk",
    label: "Fly fishing trout/salmon (AFK)",
    skillKey: "fishing",
    level: 20,
    rateBands: [
      { level: 20, xpPerHour: 13_000 },
      { level: 30, xpPerHour: 25_000 },
      { level: 40, xpPerHour: 30_000 },
      { level: 50, xpPerHour: 34_000 },
      { level: 60, xpPerHour: 37_000 },
      { level: 70, xpPerHour: 41_000 },
      { level: 80, xpPerHour: 44_000 },
      { level: 90, xpPerHour: 47_000 },
      { level: 99, xpPerHour: 50_000 },
    ],
    consumables: [{ name: "Feather", qty: 800 }],
    rewards: [{ name: "Raw salmon", expectedQtyPerHour: 400 }],
    intensity: "low",
    notes: "Wiki AFK fly-fishing table (drop time included). Mix of trout/salmon; GP uses salmon as proxy. Not 3-tick (23–93k).",
  },
  {
    id: "barbarian-fishing",
    label: "Barbarian fishing (AFK)",
    skillKey: "fishing",
    level: 48,
    rateBands: [
      { level: 48, xpPerHour: 23_000 },
      { level: 58, xpPerHour: 37_000 },
      { level: 70, xpPerHour: 48_000 },
      { level: 80, xpPerHour: 52_000 },
      { level: 90, xpPerHour: 54_000 },
      { level: 99, xpPerHour: 57_000 },
    ],
    consumables: [{ name: "Feather", qty: 700 }],
    rewards: [],
    intensity: "low",
    notes: "Wiki AFK barbarian/leaping table. Not 3-tick (41–108k).",
  },
  {
    id: "monkfish",
    label: "Monkfish",
    skillKey: "fishing",
    level: 62,
    rateBands: [
      { level: 62, xpPerHour: 35_800 },
      { level: 70, xpPerHour: 37_000 },
      { level: 80, xpPerHour: 38_500 },
      { level: 90, xpPerHour: 40_000 },
      { level: 99, xpPerHour: 42_000 },
    ],
    consumables: [],
    rewards: [{ name: "Raw monkfish", expectedQtyPerHour: 350 }],
    intensity: "low",
    notes: "Wiki monkfish XP/h table. Logs/h at 99 ≈ 42k/120.",
  },
  {
    id: "karambwan",
    label: "Karambwan",
    skillKey: "fishing",
    level: 65,
    rateBands: [
      { level: 65, xpPerHour: 29_000 },
      { level: 70, xpPerHour: 31_000 },
      { level: 75, xpPerHour: 32_900 },
      { level: 80, xpPerHour: 34_900 },
      { level: 85, xpPerHour: 36_800 },
      { level: 90, xpPerHour: 38_700 },
      { level: 95, xpPerHour: 40_600 },
      { level: 99, xpPerHour: 42_000 },
    ],
    consumables: [{ name: "Raw karambwanji", qty: 840 }],
    rewards: [{ name: "Raw karambwan", expectedQtyPerHour: 840 }],
    intensity: "medium",
    notes: "Wiki karambwan table (vessel + barrel). Qty/h at 99 = 42k/50.",
  },
  {
    id: "infernal-eel",
    label: "Infernal eel",
    skillKey: "fishing",
    level: 80,
    rateBands: [
      { level: 80, xpPerHour: 29_700 },
      { level: 90, xpPerHour: 31_800 },
      { level: 99, xpPerHour: 34_000 },
    ],
    consumables: [{ name: "Fishing bait", qty: 350 }],
    rewards: [],
    intensity: "low",
    notes: "Wiki infernal eel table. Tokkul/onyx shards not itemized.",
  },
  {
    id: "leechfin",
    label: "Leechfin",
    skillKey: "fishing",
    level: 78,
    rateBands: [
      { level: 78, xpPerHour: 109_000 },
      { level: 85, xpPerHour: 116_000 },
      { level: 90, xpPerHour: 122_000 },
      { level: 95, xpPerHour: 127_000 },
      { level: 99, xpPerHour: 130_000 },
    ],
    consumables: [],
    rewards: [],
    intensity: "high",
    notes: "Wiki leechfin table (Vampyrium, angler's). Power-fish; blood sacs not itemized.",
  },
  {
    id: "minnows",
    label: "Minnows",
    skillKey: "fishing",
    level: 82,
    rateBands: [
      { level: 82, xpPerHour: 40_000 },
      { level: 85, xpPerHour: 43_000 },
      { level: 90, xpPerHour: 45_000 },
      { level: 95, xpPerHour: 48_000 },
      { level: 99, xpPerHour: 56_000 },
    ],
    consumables: [],
    rewards: [{ name: "Raw shark", expectedQtyPerHour: 80 }],
    intensity: "medium",
    notes: "Wiki minnow table with angler's. Sharks ≈ minnows/40 at 99.",
  },
  {
    id: "sacred-eel",
    label: "Sacred eel",
    skillKey: "fishing",
    level: 87,
    rateBands: [
      { level: 87, xpPerHour: 20_000 },
      { level: 99, xpPerHour: 23_000 },
    ],
    consumables: [{ name: "Fishing bait", qty: 220 }],
    rewards: [],
    intensity: "low",
    notes: "Wiki sacred eel table. Zulrah scales not itemized.",
  },
  {
    id: "drift-net",
    label: "Drift net fishing",
    skillKey: "fishing",
    level: 44,
    secondarySkill: "hunter",
    rateBands: [
      { level: 44, xpPerHour: 54_050, secondaryXpPerHour: 60_145 },
      { level: 50, xpPerHour: 57_500, secondaryXpPerHour: 71_875 },
      { level: 55, xpPerHour: 63_250, secondaryXpPerHour: 82_225 },
      { level: 60, xpPerHour: 69_000, secondaryXpPerHour: 93_150 },
      { level: 65, xpPerHour: 74_750, secondaryXpPerHour: 104_650 },
      { level: 70, xpPerHour: 80_500, secondaryXpPerHour: 116_725 },
    ],
    consumables: [{ name: "Drift net", qty: 1150 }],
    rewards: [],
    intensity: "high",
    notes: "1,150 shoals/h × wiki XP/shoal. Fishing XP = 47–70/shoal; Hunter 52.3–101.5.",
  },
];
