import type { GearSetRow } from "./gear-sets-early";

export const GEAR_SETS_MIDLATE: GearSetRow[] = [
  { key: "lvl70-void", label: "70+ (Elite void)", tier: "late", combat: "range", items: ["Red chinchompa", "Black chinchompa", "Toxic blowpipe (empty)", "Adamant dart", "Rune dart", "Amethyst dart", "Dragon dart"] },
  { key: "lvl70-dhide", label: "70+ (Dragonhide)", tier: "late", combat: "range", items: ["Dragon crossbow", "Twisted buckler", "Diamond dragon bolts (e)", "Ruby dragon bolts (e)", "Toxic blowpipe (empty)", "Adamant dart", "Rune dart", "Amethyst dart", "Eclipse atlatl", "Atlatl dart", "Eclipse moon helm", "Eclipse moon chestplate", "Eclipse moon tassets", "Odium ward", "Antler guard"] },
  { key: "lvl75", label: "75+", tier: "late", items: ["Kraken tentacle", "Serpentine helm", "Amulet of fury", "Berserker ring", "Dragon boots", "Burning claws", "Dragon crossbow", "Twisted buckler", "Toxic blowpipe (empty)", "Dragon dart", "Amethyst dart", "Rune dart", "Necklace of anguish", "Pegasian boots", "Odium ward", "Armadyl crossbow", "Ruby dragon bolts (e)", "Diamond dragon bolts (e)", "Trident of the seas (full)", "Uncharged toxic trident", "Ancient sceptre", "Occult necklace", "Elidinis' ward", "Seers ring", "Mage's book"] },
  { key: "lvl78-powered", label: "78+ Powered stave", tier: "late", combat: "magic", items: ["Trident of the seas (full)", "Uncharged toxic trident", "Uncharged trident", "Occult necklace", "Elidinis' ward", "Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Mage's book"] },
  { key: "lvl80", label: "80+", tier: "late", items: ["Kraken tentacle", "Serpentine helm", "Amulet of torture", "Ferocious gloves", "Berserker ring", "Dragon boots", "Blood moon helm", "Blood moon chestplate", "Blood moon tassets", "Dual macuahuitl", "Burning claws", "Osmumten's fang", "Abyssal bludgeon", "Dragon warhammer", "Bandos godsword", "Bandos chestplate", "Bandos tassets", "Bandos boots", "Armadyl crossbow", "Armadyl helmet", "Armadyl chestplate", "Armadyl chainskirt", "Necklace of anguish", "Pegasian boots", "Dragon hunter crossbow", "Dragonfire ward", "Twisted buckler", "Ruby dragon bolts (e)", "Diamond dragon bolts (e)", "Toxic blowpipe (empty)", "Dragon dart", "Masori mask", "Masori body", "Masori chaps", "Webweaver bow (u)", "Scorching bow", "Dragon arrow", "Ancient sceptre", "Toxic staff (uncharged)", "Purging staff", "Dragon hunter wand", "Sanguinesti staff (uncharged)", "Eye of ayak (uncharged)", "Uncharged toxic trident", "Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Blue moon helm", "Blue moon chestplate", "Blue moon tassets", "Occult necklace", "Tormented bracelet", "Elidinis' ward"] },
  { key: "lvl85", label: "85+", tier: "late", items: ["Bow of faerdhinen (inactive)", "Crystal helm", "Crystal body", "Crystal legs", "Dragon arrow", "Armadyl crossbow", "Armadyl helmet", "Armadyl chestplate", "Armadyl chainskirt", "Necklace of anguish", "Pegasian boots", "Dragon hunter crossbow", "Dragonfire ward", "Masori mask", "Masori body", "Masori chaps", "Toxic blowpipe (empty)", "Dragon dart", "Webweaver bow (u)", "Scorching bow", "Sanguinesti staff (uncharged)", "Eye of ayak (uncharged)", "Toxic staff (uncharged)", "Purging staff", "Dragon hunter wand", "Occult necklace", "Tormented bracelet", "Eternal boots", "Confliction gauntlets", "Elidinis' ward", "Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Seers ring", "Virtus mask", "Virtus robe top", "Virtus robe bottom"] },
  { key: "lvl90", label: "90+", tier: "late", combat: "melee", items: ["Dragon hunter lance", "Voidwaker", "Dragon claws", "Noxious halberd", "Osmumten's fang", "Abyssal bludgeon", "Dragon warhammer", "Bandos godsword", "Bandos chestplate", "Bandos tassets", "Bandos boots", "Amulet of rancour", "Amulet of torture", "Ferocious gloves", "Neitiznot faceguard", "Serpentine helm", "Blood moon helm", "Blood moon chestplate", "Blood moon tassets", "Dual macuahuitl", "Burning claws", "Kraken tentacle", "Berserker ring", "Dragon boots", "Ghrazi rapier"] },
  { key: "lvl95", label: "95+", tier: "late", combat: "melee", items: ["Ghrazi rapier", "Blade of saeldor (inactive)", "Inquisitor's mace", "Dragon hunter lance", "Voidwaker", "Dragon claws", "Noxious halberd", "Osmumten's fang", "Bandos chestplate", "Bandos tassets", "Bandos boots", "Amulet of rancour", "Amulet of torture", "Ferocious gloves", "Primordial boots", "Neitiznot faceguard", "Serpentine helm", "Ultor ring", "Blood moon helm", "Blood moon chestplate", "Blood moon tassets", "Dual macuahuitl", "Burning claws", "Kraken tentacle"] },
  { key: "bandos", label: "Bandos", tier: "late", combat: "melee", items: ["Bandos chestplate", "Bandos tassets", "Bandos boots", "Amulet of torture", "Amulet of rancour", "Primordial boots", "Ferocious gloves", "Neitiznot faceguard"] },
  { key: "blood-moon", label: "Blood moon", tier: "late", combat: "melee", items: ["Blood moon helm", "Blood moon chestplate", "Blood moon tassets", "Dual macuahuitl", "Amulet of torture", "Amulet of rancour", "Ferocious gloves", "Dragon boots"] },
  { key: "armadyl", label: "Armadyl", tier: "late", combat: "range", items: ["Armadyl crossbow", "Armadyl helmet", "Armadyl chestplate", "Armadyl chainskirt", "Necklace of anguish", "Pegasian boots", "Ruby dragon bolts (e)", "Diamond dragon bolts (e)"] },
  { key: "crystal", label: "Crystal / Bowfa", tier: "late", combat: "range", items: ["Bow of faerdhinen (inactive)", "Crystal helm", "Crystal body", "Crystal legs", "Dragon arrow", "Necklace of anguish", "Pegasian boots"] },
  { key: "blue-moon", label: "Blue moon", tier: "late", combat: "magic", items: ["Blue moon helm", "Blue moon chestplate", "Blue moon tassets", "Ancient sceptre", "Occult necklace", "Tormented bracelet", "Eternal boots", "Elidinis' ward", "Eye of ayak (uncharged)"] },
];
