import type { GearSetRow } from "./gear-sets-early";

export const GEAR_SETS_END: GearSetRow[] = [
  { key: "end-slash", label: "Endgame Slash", tier: "end", combat: "melee", items: ["Blade of saeldor (inactive)", "Scythe of vitur (uncharged)", "Soulreaper axe", "Ghrazi rapier", "Amulet of rancour", "Amulet of blood fury", "Torva full helm", "Torva platebody", "Torva platelegs", "Ultor ring", "Avernic treads", "Primordial boots", "Ferocious gloves", "Neitiznot faceguard"] },
  { key: "end-crush", label: "Endgame Crush", tier: "end", combat: "melee", items: ["Inquisitor's great helm", "Inquisitor's hauberk", "Inquisitor's plateskirt", "Inquisitor's mace", "Scythe of vitur (uncharged)", "Soulreaper axe", "Amulet of rancour", "Amulet of blood fury", "Torva full helm", "Torva platebody", "Torva platelegs", "Ultor ring", "Avernic treads", "Primordial boots", "Ferocious gloves"] },
  { key: "end-stab", label: "Endgame Stab/Strength", tier: "end", combat: "melee", items: ["Ghrazi rapier", "Osmumten's fang", "Blade of saeldor (inactive)", "Scythe of vitur (uncharged)", "Soulreaper axe", "Amulet of rancour", "Amulet of blood fury", "Torva full helm", "Torva platebody", "Torva platelegs", "Ultor ring", "Avernic treads", "Primordial boots", "Ferocious gloves", "Neitiznot faceguard"] },
  { key: "end-defence", label: "Endgame Defence", tier: "end", combat: "melee", items: ["Justiciar faceguard", "Justiciar chestguard", "Justiciar legguards", "Torva full helm", "Torva platebody", "Torva platelegs", "Amulet of rancour", "Amulet of blood fury", "Primordial boots"] },
  { key: "end-xbow", label: "Endgame Crossbow", tier: "end", combat: "range", items: ["Zaryte crossbow", "Ruby dragon bolts (e)", "Diamond dragon bolts (e)", "Masori mask", "Masori body", "Masori chaps", "Masori mask (f)", "Masori body (f)", "Masori chaps (f)", "Zaryte vambraces", "Necklace of anguish", "Necklace of rupture", "Pegasian boots", "Venator ring", "Avernic treads"] },
  { key: "end-blowpipe", label: "Endgame Blowpipe", tier: "end", combat: "range", items: ["Toxic blowpipe (empty)", "Dragon dart", "Masori mask (f)", "Masori body (f)", "Masori chaps (f)", "Zaryte vambraces", "Necklace of anguish", "Necklace of rupture", "Venator ring", "Avernic treads", "Pegasian boots"] },
  { key: "end-bow", label: "Endgame Bow", tier: "end", combat: "range", items: ["Twisted bow", "Venator bow (uncharged)", "Bow of faerdhinen (inactive)", "Dragon arrow", "Masori mask (f)", "Masori body (f)", "Masori chaps (f)", "Zaryte vambraces", "Venator ring", "Necklace of anguish", "Necklace of rupture", "Avernic treads", "Pegasian boots"] },
  { key: "end-ancients", label: "Endgame Ancients", tier: "end", combat: "magic", items: ["Virtus mask", "Virtus robe top", "Virtus robe bottom", "Kodai wand", "Ancestral hat", "Ancestral robe top", "Ancestral robe bottom", "Tumeken's shadow (uncharged)", "Occult necklace", "Elidinis' ward (f)", "Confliction gauntlets", "Magus ring", "Avernic treads", "Eternal boots", "Tormented bracelet"] },
  { key: "end-elemental", label: "Endgame Elemental", tier: "end", combat: "magic", items: ["Ancestral hat", "Ancestral robe top", "Ancestral robe bottom", "Harmonised nightmare staff", "Kodai wand", "Tumeken's shadow (uncharged)", "Occult necklace", "Tome of fire", "Elidinis' ward (f)", "Confliction gauntlets", "Magus ring", "Avernic treads", "Eternal boots", "Tormented bracelet"] },
  { key: "end-demonbane", label: "Endgame Demonbane", tier: "end", combat: "magic", items: ["Purging staff", "Ancestral hat", "Ancestral robe top", "Ancestral robe bottom", "Kodai wand", "Tumeken's shadow (uncharged)", "Occult necklace", "Elidinis' ward (f)", "Confliction gauntlets", "Magus ring", "Avernic treads", "Eternal boots", "Tormented bracelet"] },
  { key: "end-megarare", label: "Endgame Megarare", tier: "end", items: ["Scythe of vitur (uncharged)", "Soulreaper axe", "Blade of saeldor (inactive)", "Ghrazi rapier", "Torva full helm", "Torva platebody", "Torva platelegs", "Ultor ring", "Amulet of rancour", "Ferocious gloves", "Primordial boots", "Twisted bow", "Zaryte crossbow", "Masori mask (f)", "Masori body (f)", "Masori chaps (f)", "Zaryte vambraces", "Venator ring", "Necklace of anguish", "Necklace of rupture", "Tumeken's shadow (uncharged)", "Harmonised nightmare staff", "Kodai wand", "Ancestral hat", "Ancestral robe top", "Ancestral robe bottom", "Occult necklace", "Elidinis' ward (f)", "Confliction gauntlets", "Magus ring", "Avernic treads", "Eternal boots", "Tormented bracelet"] },
];
