/**
 * Wiki gear-set stages under each progression tier.
 * Labels follow the cost-table headers on:
 * - https://oldschool.runescape.wiki/w/Guide:Melee_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Ranged_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Magic_Gear_Progression
 *
 * Shared stage names (20+, Pre-RfD, 75+, …) are grouped into one entry
 * across combat styles. Combat-specific sets keep a `combat` tag.
 * Item-level combat filtering still applies via catalog tags.
 * Only tradeable GE items that exist in CATALOG (exact names).
 */
export type GearSetDef = {
  key: string;
  label: string;
  tier: "early" | "mid" | "late" | "end";
  /** When set, only offered while that combat style (or All) is selected. */
  combat?: "melee" | "range" | "magic";
  items: readonly string[];
};

export const GEAR_SETS: GearSetDef[] = [
  // ── Early ──────────────────────────────────────────────
  {
    key: "lvl20",
    label: "20+",
    tier: "early",
    items: [
      // Range
      "Maple shortbow",
      "Adamant arrow",
      // Magic
      "Mystic hat (dark)",
      "Mystic robe top (dark)",
      "Mystic robe bottom (dark)",
      "Mystic gloves (dark)",
      "Mystic boots (dark)",
      "Iban's staff (u)",
    ],
  },
  {
    key: "lvl30",
    label: "30+",
    tier: "early",
    combat: "melee",
    items: [
      "Amulet of strength",
      "Combat bracelet",
      "Rune boots",
      "Berserker helm",
      "Mixed hide cape",
    ],
  },
  {
    key: "lvl40",
    label: "40+",
    tier: "early",
    items: [
      // Melee
      "Dragon scimitar",
      "Dragon boots",
      "Helm of neitiznot",
      "Amulet of strength",
      "Combat bracelet",
      "Rune boots",
      "Berserker helm",
      // Range
      "Maple shortbow",
      "Adamant arrow",
      "Magic shortbow",
      "Rune arrow",
      "Dorgeshuun crossbow",
      "Bone bolts",
      // Magic
      "Mystic hat (dark)",
      "Mystic robe top (dark)",
      "Mystic robe bottom (dark)",
      "Mystic gloves (dark)",
      "Mystic boots (dark)",
      "Iban's staff (u)",
    ],
  },
  {
    key: "dorgeshuun",
    label: "Dorgeshuun",
    tier: "early",
    combat: "range",
    items: ["Dorgeshuun crossbow", "Bone bolts"],
  },

  // ── Mid ────────────────────────────────────────────────
  {
    key: "pre-rfd",
    label: "Pre-RfD",
    tier: "mid",
    items: [
      // Melee
      "Abyssal whip",
      "Amulet of fury",
      "Zamorakian hasta",
      "Zombie axe",
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Toktz-xil-ak",
      "Toktz-xil-ek",
      "Ursine chainmace",
      "Helm of neitiznot",
      "Dragon boots",
      // Range (Level 40 Pre-RfD)
      "Dorgeshuun crossbow",
      "Bone bolts",
      "Magic shortbow",
      "Rune arrow",
      "Rune crossbow",
      "Broad bolts",
    ],
  },
  {
    key: "post-rfd",
    label: "Post-RfD",
    tier: "mid",
    items: [
      // Melee
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Zamorakian hasta",
      "Zombie axe",
      "Berserker ring",
      "Ursine chainmace",
      "Dragon boots",
      "Helm of neitiznot",
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      // Range (Level 50 Post-RfD)
      "Magic shortbow",
      "Rune arrow",
      "Amethyst arrow",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      // Magic (Level 60 Post-RfD)
      "Infinity hat",
      "Infinity top",
      "Infinity bottoms",
      "Infinity gloves",
      "Infinity boots",
      "Bloodbark helm",
      "Bloodbark body",
      "Bloodbark legs",
      "Bloodbark gauntlets",
      "Bloodbark boots",
      "Dagon'hai hat",
      "Dagon'hai robe top",
      "Dagon'hai robe bottom",
      "Warped sceptre",
      "Iban's staff (u)",
    ],
  },
  {
    key: "barrows",
    label: "Barrows",
    tier: "mid",
    combat: "melee",
    items: [
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Guthan's helm",
      "Guthan's platebody",
      "Guthan's chainskirt",
      "Guthan's warspear",
      "Torag's helm",
      "Torag's platebody",
      "Torag's platelegs",
      "Torag's hammers",
      "Verac's helm",
      "Verac's brassard",
      "Verac's plateskirt",
      "Verac's flail",
    ],
  },
  {
    key: "obsidian",
    label: "Obsidian",
    tier: "mid",
    combat: "melee",
    items: [
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Toktz-xil-ak",
      "Toktz-xil-ek",
    ],
  },
  {
    key: "lvl60",
    label: "60+",
    tier: "mid",
    combat: "range",
    items: [
      "Amethyst arrow",
      "Hunters' sunlight crossbow",
      "Sunlight antler bolts",
      "Moonlight antler bolts",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Steel cannonball",
    ],
  },
  {
    key: "lvl65",
    label: "65+",
    tier: "mid",
    combat: "melee",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Helm of neitiznot",
      "Zamorakian hasta",
      "Zombie axe",
      "Ursine chainmace",
    ],
  },
  {
    key: "lvl70",
    label: "70+",
    tier: "mid",
    items: [
      // Melee
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Helm of neitiznot",
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      // Range
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Amethyst arrow",
      "Magic shortbow",
      "Rune arrow",
      "Steel cannonball",
      "Red chinchompa",
      "Black chinchompa",
      // Magic (70+ Ancients + Elemental)
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Ahrim's staff",
      "Ancient sceptre",
      "Trident of the seas (full)",
      "Uncharged trident",
      "Occult necklace",
      "Seers ring",
      "Mage's book",
      "Tome of fire",
      "Tome of water",
      "Tome of earth",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
    ],
  },
  {
    key: "ahrims",
    label: "Ahrim's",
    tier: "mid",
    combat: "magic",
    items: ["Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Ahrim's staff"],
  },

  // ── Late ───────────────────────────────────────────────
  {
    key: "lvl70-void",
    label: "70+ (Elite void)",
    tier: "late",
    combat: "range",
    items: [
      "Red chinchompa",
      "Black chinchompa",
      "Toxic blowpipe (empty)",
      "Adamant dart",
      "Rune dart",
      "Amethyst dart",
      "Dragon dart",
    ],
  },
  {
    key: "lvl70-dhide",
    label: "70+ (Dragonhide)",
    tier: "late",
    combat: "range",
    items: [
      "Dragon crossbow",
      "Twisted buckler",
      "Diamond dragon bolts (e)",
      "Ruby dragon bolts (e)",
      "Toxic blowpipe (empty)",
      "Adamant dart",
      "Rune dart",
      "Amethyst dart",
      "Eclipse atlatl",
      "Atlatl dart",
      "Eclipse moon helm",
      "Eclipse moon chestplate",
      "Eclipse moon tassets",
      "Odium ward",
      "Antler guard",
    ],
  },
  {
    key: "lvl75",
    label: "75+",
    tier: "late",
    items: [
      // Melee
      "Kraken tentacle",
      "Serpentine helm",
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
      "Burning claws",
      "Amulet of torture",
      "Berserker ring",
      "Dragon boots",
      // Range
      "Dragon crossbow",
      "Twisted buckler",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Amethyst dart",
      "Necklace of anguish",
      "Pegasian boots",
      "Odium ward",
      "Armadyl crossbow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      // Magic (75+ Ancients)
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Ancient sceptre",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
      "Occult necklace",
      "Seers ring",
      "Mage's book",
    ],
  },
  {
    key: "lvl78-powered",
    label: "78+ Powered stave",
    tier: "late",
    combat: "magic",
    items: [
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Uncharged trident",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Mage's book",
      "Elidinis' ward",
    ],
  },
  {
    key: "lvl80",
    label: "80+",
    tier: "late",
    items: [
      // Melee
      "Osmumten's fang",
      "Abyssal bludgeon",
      "Dragon warhammer",
      "Bandos godsword",
      "Serpentine helm",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Kraken tentacle",
      // Range
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Dragon hunter crossbow",
      "Dragonfire ward",
      "Twisted buckler",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Webweaver bow (u)",
      "Scorching bow",
      "Dragon arrow",
      // Magic (80+ Ancients + Powered stave)
      "Ancient sceptre",
      "Toxic staff (uncharged)",
      "Purging staff",
      "Dragon hunter wand",
      "Sanguinesti staff (uncharged)",
      "Eye of ayak (uncharged)",
      "Uncharged toxic trident",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Elidinis' ward",
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
    ],
  },
  {
    key: "lvl85",
    label: "85+",
    tier: "late",
    items: [
      // Range
      "Bow of faerdhinen (inactive)",
      "Crystal helm",
      "Crystal body",
      "Crystal legs",
      "Dragon arrow",
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Dragon hunter crossbow",
      "Dragonfire ward",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Webweaver bow (u)",
      "Scorching bow",
      // Magic (85+ Powered stave)
      "Sanguinesti staff (uncharged)",
      "Eye of ayak (uncharged)",
      "Toxic staff (uncharged)",
      "Purging staff",
      "Dragon hunter wand",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Elidinis' ward",
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
    ],
  },
  {
    key: "lvl90",
    label: "90+",
    tier: "late",
    combat: "melee",
    items: [
      "Dragon hunter lance",
      "Voidwaker",
      "Dragon claws",
      "Noxious halberd",
      "Osmumten's fang",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Ghrazi rapier",
    ],
  },
  {
    key: "lvl95",
    label: "95+",
    tier: "late",
    combat: "melee",
    items: [
      "Ghrazi rapier",
      "Dragon hunter lance",
      "Voidwaker",
      "Dragon claws",
      "Noxious halberd",
      "Bandos chestplate",
      "Bandos tassets",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Serpentine helm",
    ],
  },
  {
    key: "bandos",
    label: "Bandos",
    tier: "late",
    combat: "melee",
    items: [
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Primordial boots",
      "Ferocious gloves",
      "Neitiznot faceguard",
    ],
  },
  {
    key: "blood-moon",
    label: "Blood moon",
    tier: "late",
    combat: "melee",
    items: [
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
    ],
  },
  {
    key: "armadyl",
    label: "Armadyl",
    tier: "late",
    combat: "range",
    items: [
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
    ],
  },
  {
    key: "crystal",
    label: "Crystal / Bowfa",
    tier: "late",
    combat: "range",
    items: [
      "Bow of faerdhinen (inactive)",
      "Crystal helm",
      "Crystal body",
      "Crystal legs",
      "Dragon arrow",
    ],
  },
  {
    key: "blue-moon",
    label: "Blue moon",
    tier: "late",
    combat: "magic",
    items: ["Blue moon helm", "Blue moon chestplate", "Blue moon tassets", "Ancient sceptre"],
  },

  // ── End ────────────────────────────────────────────────
  {
    key: "end-slash",
    label: "Endgame Slash",
    tier: "end",
    combat: "melee",
    items: [
      "Blade of saeldor (inactive)",
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Amulet of rancour",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
      "Ghrazi rapier",
    ],
  },
  {
    key: "end-crush",
    label: "Endgame Crush",
    tier: "end",
    combat: "melee",
    items: [
      "Inquisitor's great helm",
      "Inquisitor's hauberk",
      "Inquisitor's plateskirt",
      "Inquisitor's mace",
      "Amulet of blood fury",
      "Ultor ring",
      "Avernic treads",
    ],
  },
  {
    key: "end-stab",
    label: "Endgame Stab/Strength",
    tier: "end",
    combat: "melee",
    items: [
      "Ghrazi rapier",
      "Osmumten's fang",
      "Amulet of rancour",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
    ],
  },
  {
    key: "end-defence",
    label: "Endgame Defence",
    tier: "end",
    combat: "melee",
    items: [
      "Justiciar faceguard",
      "Justiciar chestguard",
      "Justiciar legguards",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
    ],
  },
  {
    key: "end-xbow",
    label: "Endgame Crossbow",
    tier: "end",
    combat: "range",
    items: [
      "Zaryte crossbow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Zaryte vambraces",
      "Necklace of anguish",
      "Pegasian boots",
    ],
  },
  {
    key: "end-blowpipe",
    label: "Endgame Blowpipe",
    tier: "end",
    combat: "range",
    items: [
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Necklace of rupture",
      "Venator ring",
      "Avernic treads",
    ],
  },
  {
    key: "end-bow",
    label: "Endgame Bow",
    tier: "end",
    combat: "range",
    items: [
      "Twisted bow",
      "Venator bow (uncharged)",
      "Dragon arrow",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Venator ring",
      "Necklace of rupture",
      "Avernic treads",
    ],
  },
  {
    key: "end-ancients",
    label: "Endgame Ancients",
    tier: "end",
    combat: "magic",
    items: [
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
      "Kodai wand",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Tumeken's shadow (uncharged)",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
      "Eternal boots",
      "Tormented bracelet",
    ],
  },
  {
    key: "end-elemental",
    label: "Endgame Elemental",
    tier: "end",
    combat: "magic",
    items: [
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Harmonised nightmare staff",
      "Kodai wand",
      "Tumeken's shadow (uncharged)",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
    ],
  },
  {
    key: "end-demonbane",
    label: "Endgame Demonbane",
    tier: "end",
    combat: "magic",
    items: [
      "Purging staff",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Kodai wand",
      "Tumeken's shadow (uncharged)",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
    ],
  },
  {
    key: "end-megarare",
    label: "Endgame Megarare",
    tier: "end",
    items: [
      // Melee
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Blade of saeldor (inactive)",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Amulet of rancour",
      // Range
      "Twisted bow",
      "Zaryte crossbow",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Venator ring",
      "Necklace of rupture",
      // Magic
      "Tumeken's shadow (uncharged)",
      "Harmonised nightmare staff",
      "Kodai wand",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
    ],
  },
  {
    key: "torva",
    label: "Torva",
    tier: "end",
    combat: "melee",
    items: ["Torva full helm", "Torva platebody", "Torva platelegs", "Ultor ring"],
  },
  {
    key: "masori",
    label: "Masori",
    tier: "end",
    combat: "range",
    items: [
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
    ],
  },
  {
    key: "ancestral",
    label: "Ancestral",
    tier: "end",
    combat: "magic",
    items: ["Ancestral hat", "Ancestral robe top", "Ancestral robe bottom"],
  },
];

export function gearSetsForTier(
  tier: string,
  combat: string,
): GearSetDef[] {
  if (tier === "all") return [];
  return GEAR_SETS.filter(
    (s) =>
      s.tier === tier &&
      (!s.combat || combat === "all" || s.combat === combat),
  );
}

export function gearSetItemNames(setKey: string): Set<string> | null {
  if (!setKey || setKey === "all") return null;
  const def = GEAR_SETS.find((s) => s.key === setKey);
  return def ? new Set(def.items) : null;
}
