/** Extra tradeable PvM items layered onto wiki progression sets. */
const EXTRA_SET_ITEMS: Record<string, readonly string[]> = {
  "post-rfd": ["Archers ring", "Ring of the gods", "Tyrannical ring", "Treasonous ring", "Master wand"],
  lvl65: ["Tyrannical ring", "Treasonous ring", "Ring of the gods"],
  lvl70: [
    "Archers ring",
    "Ring of the gods",
    "Tyrannical ring",
    "Treasonous ring",
    "Sunfire fanatic helm",
    "Sunfire fanatic cuirass",
    "Sunfire fanatic chausses",
    "Master wand",
  ],
  lvl75: [
    "Archers ring",
    "Lightbearer",
    "Ring of suffering",
    "Ring of the gods",
    "Sunfire fanatic helm",
    "Sunfire fanatic cuirass",
    "Sunfire fanatic chausses",
  ],
  lvl80: [
    "Saradomin godsword",
    "Armadyl godsword",
    "Zamorak godsword",
    "Avernic defender hilt",
    "Tormented synapse",
    "Lightbearer",
    "Bellator ring",
    "Ring of suffering",
    "Archers ring",
    "Sunfire fanatic helm",
    "Sunfire fanatic cuirass",
    "Sunfire fanatic chausses",
  ],
  lvl85: ["Lightbearer", "Ring of suffering", "Archers ring", "Master wand"],
  lvl90: [
    "Saradomin godsword",
    "Armadyl godsword",
    "Zamorak godsword",
    "Avernic defender hilt",
    "Lightbearer",
    "Bellator ring",
    "Ring of suffering",
    "Tyrannical ring",
    "Treasonous ring",
  ],
  lvl95: [
    "Saradomin godsword",
    "Armadyl godsword",
    "Zamorak godsword",
    "Avernic defender hilt",
    "Lightbearer",
    "Bellator ring",
    "Ring of suffering",
    "Tormented synapse",
  ],
  bandos: ["Avernic defender hilt", "Bellator ring", "Lightbearer"],
  "blood-moon": ["Lightbearer", "Bellator ring"],
  armadyl: ["Archers ring", "Lightbearer"],
  crystal: ["Archers ring", "Lightbearer"],
  "blue-moon": ["Master wand", "Lightbearer", "Ring of suffering"],
  "end-slash": ["Bellator ring", "Lightbearer", "Avernic defender hilt", "Saradomin godsword", "Armadyl godsword"],
  "end-crush": ["Tyrannical ring", "Lightbearer", "Avernic defender hilt"],
  "end-stab": ["Treasonous ring", "Lightbearer", "Avernic defender hilt"],
  "end-defence": [
    "Ring of suffering",
    "Ring of the gods",
    "Avernic defender hilt",
    "Sunfire fanatic helm",
    "Sunfire fanatic cuirass",
    "Sunfire fanatic chausses",
  ],
  "end-xbow": ["Archers ring", "Lightbearer", "Ring of suffering"],
  "end-blowpipe": ["Archers ring", "Lightbearer"],
  "end-bow": ["Archers ring", "Lightbearer"],
  "end-ancients": ["Lightbearer", "Ring of suffering", "Master wand"],
  "end-elemental": ["Lightbearer", "Master wand"],
  "end-demonbane": ["Tormented synapse", "Lightbearer"],
  "end-megarare": [
    "Bellator ring",
    "Lightbearer",
    "Ring of suffering",
    "Saradomin godsword",
    "Armadyl godsword",
    "Zamorak godsword",
    "Avernic defender hilt",
    "Archers ring",
  ],
};

export function extraItemsForSet(setKey: string): readonly string[] {
  return EXTRA_SET_ITEMS[setKey] ?? [];
}
