/**
 * Wiki gear-set stages under each progression tier.
 * Labels and grouping follow the cost-table headers on:
 * - https://oldschool.runescape.wiki/w/Guide:Melee_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Ranged_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Magic_Gear_Progression
 *
 * Only tradeable GE items that exist in CATALOG (exact names).
 * Our coarse tier tags: early | mid | late | end map roughly to
 * free-to-play / early members → mid game → late bossing → endgame setups.
 */
export type GearSetDef = {
  key: string;
  label: string;
  tier: "early" | "mid" | "late" | "end";
  /** When set, only offered while that combat style (or All) is selected. */
  combat?: "melee" | "range" | "magic";
  items: readonly string[];
};

export const GEAR_SETS: GearSetDef[] = [
  // ═══════════════════════════════════════════════════════
  // MELEE — Guide:Melee_Gear_Progression
  // Tables: Level 1/5/20/30/40+ → Pre/Post-RfD, 65+, 70+
  //         → 75+/80+/90+/95+ → Endgame Slash/Crush/Stab/Megarare/Defence
  // ═══════════════════════════════════════════════════════

  // Early (Level 1–40+)
  {
    key: "melee-lvl30",
    label: "Level 30",
    tier: "early",
    combat: "melee",
    items: [
      "Amulet of strength",
      "Combat bracelet",
      "Rune boots",
      "Berserker helm",
      "Mixed hide cape",
    ],
  },
  {
    key: "melee-lvl40",
    label: "Level 40+",
    tier: "early",
    combat: "melee",
    items: [
      "Dragon scimitar",
      "Dragon boots",
      "Helm of neitiznot",
      "Amulet of strength",
      "Combat bracelet",
      "Rune boots",
      "Berserker helm",
    ],
  },

  // Mid (Pre/Post-RfD, 65+, 70+)
  {
    key: "melee-pre-rfd",
    label: "Pre-RfD",
    tier: "mid",
    combat: "melee",
    items: [
      "Abyssal whip",
      "Amulet of fury",
      "Zamorakian hasta",
      "Zombie axe",
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Toktz-xil-ak",
      "Toktz-xil-ek",
      "Ursine chainmace",
      "Helm of neitiznot",
      "Dragon boots",
    ],
  },
  {
    key: "melee-post-rfd",
    label: "Post-RfD",
    tier: "mid",
    combat: "melee",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Zamorakian hasta",
      "Zombie axe",
      "Berserker ring",
      "Ursine chainmace",
      "Dragon boots",
      "Helm of neitiznot",
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
    ],
  },
  {
    key: "melee-barrows",
    label: "Barrows",
    tier: "mid",
    combat: "melee",
    items: [
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Guthan's helm",
      "Guthan's platebody",
      "Guthan's chainskirt",
      "Guthan's warspear",
      "Torag's helm",
      "Torag's platebody",
      "Torag's platelegs",
      "Torag's hammers",
      "Verac's helm",
      "Verac's brassard",
      "Verac's plateskirt",
      "Verac's flail",
    ],
  },
  {
    key: "melee-obsidian",
    label: "Obsidian",
    tier: "mid",
    combat: "melee",
    items: [
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Toktz-xil-ak",
      "Toktz-xil-ek",
    ],
  },
  {
    key: "melee-65",
    label: "Level 65+",
    tier: "mid",
    combat: "melee",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Helm of neitiznot",
      "Zamorakian hasta",
      "Zombie axe",
      "Ursine chainmace",
    ],
  },
  {
    key: "melee-70",
    label: "Level 70+",
    tier: "mid",
    combat: "melee",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Helm of neitiznot",
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
    ],
  },

  // Late (75+ / 80+ / 90+ / 95+)
  {
    key: "melee-75",
    label: "75+",
    tier: "late",
    combat: "melee",
    items: [
      "Kraken tentacle",
      "Serpentine helm",
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
      "Burning claws",
      "Amulet of torture",
      "Berserker ring",
      "Dragon boots",
    ],
  },
  {
    key: "melee-80",
    label: "80+",
    tier: "late",
    combat: "melee",
    items: [
      "Osmumten's fang",
      "Abyssal bludgeon",
      "Dragon warhammer",
      "Bandos godsword",
      "Serpentine helm",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Kraken tentacle",
    ],
  },
  {
    key: "melee-90",
    label: "90+",
    tier: "late",
    combat: "melee",
    items: [
      "Dragon hunter lance",
      "Voidwaker",
      "Dragon claws",
      "Noxious halberd",
      "Osmumten's fang",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Ghrazi rapier",
    ],
  },
  {
    key: "melee-95",
    label: "95+",
    tier: "late",
    combat: "melee",
    items: [
      "Ghrazi rapier",
      "Dragon hunter lance",
      "Voidwaker",
      "Dragon claws",
      "Noxious halberd",
      "Bandos chestplate",
      "Bandos tassets",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Serpentine helm",
    ],
  },
  {
    key: "melee-bandos",
    label: "Bandos",
    tier: "late",
    combat: "melee",
    items: [
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Primordial boots",
      "Ferocious gloves",
      "Neitiznot faceguard",
    ],
  },
  {
    key: "melee-blood-moon",
    label: "Blood moon",
    tier: "late",
    combat: "melee",
    items: [
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
    ],
  },

  // Endgame
  {
    key: "melee-end-slash",
    label: "Endgame Slash",
    tier: "end",
    combat: "melee",
    items: [
      "Blade of saeldor (inactive)",
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Amulet of rancour",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
      "Ghrazi rapier",
    ],
  },
  {
    key: "melee-end-crush",
    label: "Endgame Crush",
    tier: "end",
    combat: "melee",
    items: [
      "Inquisitor's great helm",
      "Inquisitor's hauberk",
      "Inquisitor's plateskirt",
      "Inquisitor's mace",
      "Amulet of blood fury",
      "Ultor ring",
      "Avernic treads",
    ],
  },
  {
    key: "melee-end-stab",
    label: "Endgame Stab/Strength",
    tier: "end",
    combat: "melee",
    items: [
      "Ghrazi rapier",
      "Osmumten's fang",
      "Amulet of rancour",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
    ],
  },
  {
    key: "melee-end-megarare",
    label: "Endgame Megarare",
    tier: "end",
    combat: "melee",
    items: [
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Blade of saeldor (inactive)",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Amulet of rancour",
    ],
  },
  {
    key: "melee-end-defence",
    label: "Endgame Defence",
    tier: "end",
    combat: "melee",
    items: [
      "Justiciar faceguard",
      "Justiciar chestguard",
      "Justiciar legguards",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
    ],
  },
  {
    key: "melee-torva",
    label: "Torva",
    tier: "end",
    combat: "melee",
    items: ["Torva full helm", "Torva platebody", "Torva platelegs", "Ultor ring"],
  },

  // ═══════════════════════════════════════════════════════
  // RANGED — Guide:Ranged_Gear_Progression
  // Tables: Level 1/20/40+ → Pre-RfD / Post-RfD / 60 / 70
  //         → 70 Elite void / 70 Dragonhide / 75 / 80 / 85+
  //         → Endgame Crossbow / Blowpipe / Bow / Megarare / Elite Void
  // ═══════════════════════════════════════════════════════

  // Early
  {
    key: "range-lvl20",
    label: "Level 20",
    tier: "early",
    combat: "range",
    items: ["Maple shortbow", "Adamant arrow"],
  },
  {
    key: "range-lvl40",
    label: "Level 40+",
    tier: "early",
    combat: "range",
    items: [
      "Maple shortbow",
      "Adamant arrow",
      "Magic shortbow",
      "Rune arrow",
      "Dorgeshuun crossbow",
      "Bone bolts",
    ],
  },
  {
    key: "range-dorgeshuun",
    label: "Dorgeshuun",
    tier: "early",
    combat: "range",
    items: ["Dorgeshuun crossbow", "Bone bolts"],
  },

  // Mid
  {
    key: "range-pre-rfd",
    label: "Level 40 (Pre-RfD)",
    tier: "mid",
    combat: "range",
    items: [
      "Dorgeshuun crossbow",
      "Bone bolts",
      "Magic shortbow",
      "Rune arrow",
      "Rune crossbow",
      "Broad bolts",
    ],
  },
  {
    key: "range-post-rfd",
    label: "Level 50 (Post-RfD)",
    tier: "mid",
    combat: "range",
    items: [
      "Magic shortbow",
      "Rune arrow",
      "Amethyst arrow",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
    ],
  },
  {
    key: "range-60",
    label: "Level 60",
    tier: "mid",
    combat: "range",
    items: [
      "Amethyst arrow",
      "Hunters' sunlight crossbow",
      "Sunlight antler bolts",
      "Moonlight antler bolts",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Steel cannonball",
    ],
  },
  {
    key: "range-70",
    label: "Level 70",
    tier: "mid",
    combat: "range",
    items: [
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Amethyst arrow",
      "Magic shortbow",
      "Rune arrow",
      "Steel cannonball",
      "Red chinchompa",
      "Black chinchompa",
    ],
  },

  // Late
  {
    key: "range-70-void",
    label: "Level 70 (Elite void)",
    tier: "late",
    combat: "range",
    items: [
      "Red chinchompa",
      "Black chinchompa",
      "Toxic blowpipe (empty)",
      "Adamant dart",
      "Rune dart",
      "Amethyst dart",
      "Dragon dart",
    ],
  },
  {
    key: "range-70-dhide",
    label: "Level 70 (Dragonhide)",
    tier: "late",
    combat: "range",
    items: [
      "Dragon crossbow",
      "Twisted buckler",
      "Diamond dragon bolts (e)",
      "Ruby dragon bolts (e)",
      "Toxic blowpipe (empty)",
      "Adamant dart",
      "Rune dart",
      "Amethyst dart",
      "Eclipse atlatl",
      "Atlatl dart",
      "Eclipse moon helm",
      "Eclipse moon chestplate",
      "Eclipse moon tassets",
      "Odium ward",
      "Antler guard",
    ],
  },
  {
    key: "range-75",
    label: "Level 75",
    tier: "late",
    combat: "range",
    items: [
      "Dragon crossbow",
      "Twisted buckler",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Amethyst dart",
      "Necklace of anguish",
      "Pegasian boots",
      "Odium ward",
      "Armadyl crossbow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
    ],
  },
  {
    key: "range-80",
    label: "Level 80",
    tier: "late",
    combat: "range",
    items: [
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Dragon hunter crossbow",
      "Dragonfire ward",
      "Twisted buckler",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Webweaver bow (u)",
      "Scorching bow",
      "Dragon arrow",
    ],
  },
  {
    key: "range-85",
    label: "Level 85+",
    tier: "late",
    combat: "range",
    items: [
      "Bow of faerdhinen (inactive)",
      "Crystal helm",
      "Crystal body",
      "Crystal legs",
      "Dragon arrow",
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Dragon hunter crossbow",
      "Dragonfire ward",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Webweaver bow (u)",
      "Scorching bow",
    ],
  },
  {
    key: "range-armadyl",
    label: "Armadyl",
    tier: "late",
    combat: "range",
    items: [
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
    ],
  },
  {
    key: "range-crystal",
    label: "Crystal / Bowfa",
    tier: "late",
    combat: "range",
    items: [
      "Bow of faerdhinen (inactive)",
      "Crystal helm",
      "Crystal body",
      "Crystal legs",
      "Dragon arrow",
    ],
  },

  // Endgame
  {
    key: "range-end-xbow",
    label: "Endgame Crossbow",
    tier: "end",
    combat: "range",
    items: [
      "Zaryte crossbow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Zaryte vambraces",
      "Necklace of anguish",
      "Pegasian boots",
    ],
  },
  {
    key: "range-end-blowpipe",
    label: "Endgame Blowpipe",
    tier: "end",
    combat: "range",
    items: [
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Necklace of rupture",
      "Venator ring",
      "Avernic treads",
    ],
  },
  {
    key: "range-end-bow",
    label: "Endgame Bow",
    tier: "end",
    combat: "range",
    items: [
      "Twisted bow",
      "Venator bow (uncharged)",
      "Dragon arrow",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Venator ring",
      "Necklace of rupture",
      "Avernic treads",
    ],
  },
  {
    key: "range-end-megarare",
    label: "Endgame Megarare",
    tier: "end",
    combat: "range",
    items: [
      "Twisted bow",
      "Zaryte crossbow",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Venator ring",
      "Necklace of rupture",
      "Avernic treads",
    ],
  },
  {
    key: "range-masori",
    label: "Masori",
    tier: "end",
    combat: "range",
    items: [
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
    ],
  },

  // ═══════════════════════════════════════════════════════
  // MAGIC — Guide:Magic_Gear_Progression
  // Tables: Level 1 → 20 / 40 / 60 Post-RfD / 70+ Ancients / 70+ Elemental
  //         → 75+ Ancients / 78+ Powered stave / 80+ Ancients / 80+ Powered / 85+ Powered
  //         → Endgame Ancients / Elemental / Demonbane / Megarare / Elite void
  // ═══════════════════════════════════════════════════════

  // Early
  {
    key: "magic-lvl20",
    label: "Level 20",
    tier: "early",
    combat: "magic",
    items: [
      "Mystic hat (dark)",
      "Mystic robe top (dark)",
      "Mystic robe bottom (dark)",
      "Mystic gloves (dark)",
      "Mystic boots (dark)",
      "Iban's staff (u)",
    ],
  },
  {
    key: "magic-lvl40",
    label: "Level 40",
    tier: "early",
    combat: "magic",
    items: [
      "Mystic hat (dark)",
      "Mystic robe top (dark)",
      "Mystic robe bottom (dark)",
      "Mystic gloves (dark)",
      "Mystic boots (dark)",
      "Iban's staff (u)",
    ],
  },

  // Mid
  {
    key: "magic-post-rfd",
    label: "Level 60 (Post-RfD)",
    tier: "mid",
    combat: "magic",
    items: [
      "Infinity hat",
      "Infinity top",
      "Infinity bottoms",
      "Infinity gloves",
      "Infinity boots",
      "Bloodbark helm",
      "Bloodbark body",
      "Bloodbark legs",
      "Bloodbark gauntlets",
      "Bloodbark boots",
      "Dagon'hai hat",
      "Dagon'hai robe top",
      "Dagon'hai robe bottom",
      "Warped sceptre",
      "Iban's staff (u)",
    ],
  },
  {
    key: "magic-70-ancients",
    label: "70+ Ancients",
    tier: "mid",
    combat: "magic",
    items: [
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Ahrim's staff",
      "Ancient sceptre",
      "Occult necklace",
      "Seers ring",
      "Mage's book",
      "Tome of fire",
      "Tome of water",
      "Tome of earth",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
    ],
  },
  {
    key: "magic-70-elemental",
    label: "70+ Elemental",
    tier: "mid",
    combat: "magic",
    items: [
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Ahrim's staff",
      "Trident of the seas (full)",
      "Uncharged trident",
      "Occult necklace",
      "Seers ring",
      "Mage's book",
      "Tome of fire",
      "Tome of water",
      "Tome of earth",
    ],
  },
  {
    key: "magic-ahrims",
    label: "Ahrim's",
    tier: "mid",
    combat: "magic",
    items: ["Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Ahrim's staff"],
  },

  // Late
  {
    key: "magic-75-ancients",
    label: "75+ Ancients",
    tier: "late",
    combat: "magic",
    items: [
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Ancient sceptre",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
      "Occult necklace",
      "Seers ring",
      "Mage's book",
    ],
  },
  {
    key: "magic-78-powered",
    label: "78+ Powered stave",
    tier: "late",
    combat: "magic",
    items: [
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Uncharged trident",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Mage's book",
      "Elidinis' ward",
    ],
  },
  {
    key: "magic-80-ancients",
    label: "80+ Ancients",
    tier: "late",
    combat: "magic",
    items: [
      "Ancient sceptre",
      "Toxic staff (uncharged)",
      "Purging staff",
      "Dragon hunter wand",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
    ],
  },
  {
    key: "magic-80-powered",
    label: "80+ Powered stave",
    tier: "late",
    combat: "magic",
    items: [
      "Uncharged toxic trident",
      "Sanguinesti staff (uncharged)",
      "Eye of ayak (uncharged)",
      "Toxic staff (uncharged)",
      "Dragon hunter wand",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Elidinis' ward",
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
    ],
  },
  {
    key: "magic-85-powered",
    label: "85+ Powered stave",
    tier: "late",
    combat: "magic",
    items: [
      "Sanguinesti staff (uncharged)",
      "Eye of ayak (uncharged)",
      "Toxic staff (uncharged)",
      "Purging staff",
      "Dragon hunter wand",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Elidinis' ward",
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
    ],
  },
  {
    key: "magic-blue-moon",
    label: "Blue moon",
    tier: "late",
    combat: "magic",
    items: ["Blue moon helm", "Blue moon chestplate", "Blue moon tassets", "Ancient sceptre"],
  },

  // Endgame
  {
    key: "magic-end-ancients",
    label: "Endgame Ancients",
    tier: "end",
    combat: "magic",
    items: [
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
      "Kodai wand",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Tumeken's shadow (uncharged)",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
      "Eternal boots",
      "Tormented bracelet",
    ],
  },
  {
    key: "magic-end-elemental",
    label: "Endgame Elemental",
    tier: "end",
    combat: "magic",
    items: [
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Harmonised nightmare staff",
      "Kodai wand",
      "Tumeken's shadow (uncharged)",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
    ],
  },
  {
    key: "magic-end-demonbane",
    label: "Endgame Demonbane",
    tier: "end",
    combat: "magic",
    items: [
      "Purging staff",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Kodai wand",
      "Tumeken's shadow (uncharged)",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
    ],
  },
  {
    key: "magic-end-megarare",
    label: "Endgame Megarare",
    tier: "end",
    combat: "magic",
    items: [
      "Tumeken's shadow (uncharged)",
      "Harmonised nightmare staff",
      "Kodai wand",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
    ],
  },
  {
    key: "magic-ancestral",
    label: "Ancestral",
    tier: "end",
    combat: "magic",
    items: ["Ancestral hat", "Ancestral robe top", "Ancestral robe bottom"],
  },
];

export function gearSetsForTier(
  tier: string,
  combat: string,
): GearSetDef[] {
  if (tier === "all") return [];
  return GEAR_SETS.filter(
    (s) =>
      s.tier === tier &&
      (!s.combat || combat === "all" || s.combat === combat),
  );
}

export function gearSetItemNames(setKey: string): Set<string> | null {
  if (!setKey || setKey === "all") return null;
  const def = GEAR_SETS.find((s) => s.key === setKey);
  return def ? new Set(def.items) : null;
}
