/**
 * Wiki gear-set stages under each progression tier.
 * Labels follow the cost-table headers on:
 * - https://oldschool.runescape.wiki/w/Guide:Melee_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Ranged_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Magic_Gear_Progression
 *
 * Shared stage names (20+, Pre-RfD, 75+, …) are grouped into one entry
 * across combat styles. Combat-specific sets keep a `combat` tag.
 * Item-level combat filtering still applies via catalog tags.
 * Only tradeable GE items that exist in CATALOG (exact names).
 *
 * Items that appear in multiple wiki loadouts are listed in each matching set
 * (e.g. Amulet of rancour on 90+, 95+, and endgame stages).
 */
export type GearSetDef = {
  key: string;
  label: string;
  tier: "early" | "mid" | "late" | "end";
  /** When set, only offered while that combat style (or All) is selected. */
  combat?: "melee" | "range" | "magic";
  items: readonly string[];
};

export const GEAR_SETS: GearSetDef[] = [
  // ── Early ──────────────────────────────────────────────
  {
    key: "lvl20",
    label: "20+",
    tier: "early",
    items: [
      "Maple shortbow",
      "Adamant arrow",
      "Mystic hat (dark)",
      "Mystic robe top (dark)",
      "Mystic robe bottom (dark)",
      "Mystic gloves (dark)",
      "Mystic boots (dark)",
      "Iban's staff (u)",
    ],
  },
  {
    key: "lvl30",
    label: "30+",
    tier: "early",
    combat: "melee",
    items: [
      "Amulet of strength",
      "Combat bracelet",
      "Rune boots",
      "Berserker helm",
      "Mixed hide cape",
    ],
  },
  {
    key: "lvl40",
    label: "40+",
    tier: "early",
    items: [
      "Dragon scimitar",
      "Dragon boots",
      "Helm of neitiznot",
      "Amulet of strength",
      "Combat bracelet",
      "Rune boots",
      "Berserker helm",
      "Maple shortbow",
      "Adamant arrow",
      "Magic shortbow",
      "Rune arrow",
      "Dorgeshuun crossbow",
      "Bone bolts",
      "Mystic hat (dark)",
      "Mystic robe top (dark)",
      "Mystic robe bottom (dark)",
      "Mystic gloves (dark)",
      "Mystic boots (dark)",
      "Iban's staff (u)",
    ],
  },
  {
    key: "dorgeshuun",
    label: "Dorgeshuun",
    tier: "early",
    combat: "range",
    items: ["Dorgeshuun crossbow", "Bone bolts"],
  },
  {
    key: "pre-rfd",
    label: "Pre-RfD",
    tier: "mid",
    items: [
      "Abyssal whip",
      "Amulet of fury",
      "Zamorakian hasta",
      "Zombie axe",
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Toktz-xil-ak",
      "Toktz-xil-ek",
      "Ursine chainmace",
      "Helm of neitiznot",
      "Dragon boots",
      "Dorgeshuun crossbow",
      "Bone bolts",
      "Magic shortbow",
      "Rune arrow",
      "Rune crossbow",
      "Broad bolts",
    ],
  },
  {
    key: "post-rfd",
    label: "Post-RfD",
    tier: "mid",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Zamorakian hasta",
      "Zombie axe",
      "Berserker ring",
      "Ursine chainmace",
      "Dragon boots",
      "Helm of neitiznot",
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Magic shortbow",
      "Rune arrow",
      "Amethyst arrow",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Infinity hat",
      "Infinity top",
      "Infinity bottoms",
      "Infinity gloves",
      "Infinity boots",
      "Bloodbark helm",
      "Bloodbark body",
      "Bloodbark legs",
      "Bloodbark gauntlets",
      "Bloodbark boots",
      "Dagon'hai hat",
      "Dagon'hai robe top",
      "Dagon'hai robe bottom",
      "Warped sceptre",
      "Iban's staff (u)",
    ],
  },
  {
    key: "barrows",
    label: "Barrows",
    tier: "mid",
    combat: "melee",
    items: [
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Guthan's helm",
      "Guthan's platebody",
      "Guthan's chainskirt",
      "Guthan's warspear",
      "Torag's helm",
      "Torag's platebody",
      "Torag's platelegs",
      "Torag's hammers",
      "Verac's helm",
      "Verac's brassard",
      "Verac's plateskirt",
      "Verac's flail",
    ],
  },
  {
    key: "obsidian",
    label: "Obsidian",
    tier: "mid",
    combat: "melee",
    items: [
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Toktz-xil-ak",
      "Toktz-xil-ek",
    ],
  },
  {
    key: "lvl60",
    label: "60+",
    tier: "mid",
    combat: "range",
    items: [
      "Amethyst arrow",
      "Hunters' sunlight crossbow",
      "Sunlight antler bolts",
      "Moonlight antler bolts",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Steel cannonball",
    ],
  },
  {
    key: "lvl65",
    label: "65+",
    tier: "mid",
    combat: "melee",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Helm of neitiznot",
      "Zamorakian hasta",
      "Zombie axe",
      "Ursine chainmace",
    ],
  },
  {
    key: "lvl70",
    label: "70+",
    tier: "mid",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Helm of neitiznot",
      "Dharok's helm",
      "Dharok's platebody",
      "Dharok's platelegs",
      "Dharok's greataxe",
      "Obsidian helmet",
      "Obsidian platebody",
      "Obsidian platelegs",
      "Berserker necklace",
      "Rune crossbow",
      "Broad bolts",
      "Diamond bolts (e)",
      "Ruby bolts (e)",
      "Amethyst arrow",
      "Magic shortbow",
      "Rune arrow",
      "Steel cannonball",
      "Red chinchompa",
      "Black chinchompa",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Ahrim's staff",
      "Ancient sceptre",
      "Trident of the seas (full)",
      "Uncharged trident",
      "Occult necklace",
      "Seers ring",
      "Mage's book",
      "Tome of fire",
      "Tome of water",
      "Tome of earth",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
    ],
  },
  {
    key: "ahrims",
    label: "Ahrim's",
    tier: "mid",
    combat: "magic",
    items: ["Ahrim's hood", "Ahrim's robetop", "Ahrim's robeskirt", "Ahrim's staff"],
  },
  {
    key: "lvl70-void",
    label: "70+ (Elite void)",
    tier: "late",
    combat: "range",
    items: [
      "Red chinchompa",
      "Black chinchompa",
      "Toxic blowpipe (empty)",
      "Adamant dart",
      "Rune dart",
      "Amethyst dart",
      "Dragon dart",
    ],
  },
  {
    key: "lvl70-dhide",
    label: "70+ (Dragonhide)",
    tier: "late",
    combat: "range",
    items: [
      "Dragon crossbow",
      "Twisted buckler",
      "Diamond dragon bolts (e)",
      "Ruby dragon bolts (e)",
      "Toxic blowpipe (empty)",
      "Adamant dart",
      "Rune dart",
      "Amethyst dart",
      "Eclipse atlatl",
      "Atlatl dart",
      "Eclipse moon helm",
      "Eclipse moon chestplate",
      "Eclipse moon tassets",
      "Odium ward",
      "Antler guard",
    ],
  },
  {
    key: "lvl75",
    label: "75+",
    tier: "late",
    items: [
      "Kraken tentacle",
      "Serpentine helm",
      "Amulet of fury",
      "Berserker ring",
      "Dragon boots",
      "Burning claws",
      "Dragon crossbow",
      "Twisted buckler",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Amethyst dart",
      "Rune dart",
      "Necklace of anguish",
      "Pegasian boots",
      "Odium ward",
      "Armadyl crossbow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Ancient sceptre",
      "Occult necklace",
      "Elidinis' ward",
      "Seers ring",
      "Mage's book",
    ],
  },
  {
    key: "lvl78-powered",
    label: "78+ Powered stave",
    tier: "late",
    combat: "magic",
    items: [
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Uncharged trident",
      "Occult necklace",
      "Elidinis' ward",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Mage's book",
    ],
  },
  {
    key: "lvl80",
    label: "80+",
    tier: "late",
    items: [
      "Kraken tentacle",
      "Serpentine helm",
      "Amulet of torture",
      "Ferocious gloves",
      "Berserker ring",
      "Dragon boots",
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
      "Burning claws",
      "Osmumten's fang",
      "Abyssal bludgeon",
      "Dragon warhammer",
      "Bandos godsword",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Dragon hunter crossbow",
      "Dragonfire ward",
      "Twisted buckler",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Webweaver bow (u)",
      "Scorching bow",
      "Dragon arrow",
      "Ancient sceptre",
      "Toxic staff (uncharged)",
      "Purging staff",
      "Dragon hunter wand",
      "Sanguinesti staff (uncharged)",
      "Eye of ayak (uncharged)",
      "Uncharged toxic trident",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
      "Occult necklace",
      "Tormented bracelet",
      "Elidinis' ward",
    ],
  },
  {
    key: "lvl85",
    label: "85+",
    tier: "late",
    items: [
      "Bow of faerdhinen (inactive)",
      "Crystal helm",
      "Crystal body",
      "Crystal legs",
      "Dragon arrow",
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Dragon hunter crossbow",
      "Dragonfire ward",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Webweaver bow (u)",
      "Scorching bow",
      "Sanguinesti staff (uncharged)",
      "Eye of ayak (uncharged)",
      "Toxic staff (uncharged)",
      "Purging staff",
      "Dragon hunter wand",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Confliction gauntlets",
      "Elidinis' ward",
      "Ahrim's hood",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Seers ring",
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
    ],
  },
  {
    key: "lvl90",
    label: "90+",
    tier: "late",
    combat: "melee",
    items: [
      "Dragon hunter lance",
      "Voidwaker",
      "Dragon claws",
      "Noxioushalberd",
      "Osmumten's fang",
      "Abyssal bludgeon",
      "Dragon warhammer",
      "Bandos godsword",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of rancour",
      "Amulet of torture",
      "Ferocious gloves",
      "Neitiznot faceguard",
      "Serpentine helm",
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
      "Burning claws",
      "Kraken tentacle",
      "Berserker ring",
      "Dragon boots",
      "Ghrazi rapier",
    ],
  },
  {
    key: "lvl95",
    label: "95+",
    tier: "late",
    combat: "melee",
    items: [
      "Ghrazi rapier",
      "Blade of saeldor (inactive)",
      "Inquisitor's mace",
      "Dragon hunter lance",
      "Voidwaker",
      "Dragon claws",
      "Noxioushalberd",
      "Osmumten's fang",
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of rancour",
      "Amulet of torture",
      "Ferocious gloves",
      "Primordial boots",
      "Neitiznot faceguard",
      "Serpentine helm",
      "Ultor ring",
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
      "Burning claws",
      "Kraken tentacle",
    ],
  },
  {
    key: "bandos",
    label: "Bandos",
    tier: "late",
    combat: "melee",
    items: [
      "Bandos chestplate",
      "Bandos tassets",
      "Bandos boots",
      "Amulet of torture",
      "Amulet of rancour",
      "Primordial boots",
      "Ferocious gloves",
      "Neitiznot faceguard",
    ],
  },
  {
    key: "blood-moon",
    label: "Blood moon",
    tier: "late",
    combat: "melee",
    items: [
      "Blood moon helm",
      "Blood moon chestplate",
      "Blood moon tassets",
      "Dual macuahuitl",
      "Amulet of torture",
      "Amulet of rancour",
      "Ferocious gloves",
      "Dragon boots",
    ],
  },
  {
    key: "armadyl",
    label: "Armadyl",
    tier: "late",
    combat: "range",
    items: [
      "Armadyl crossbow",
      "Armadyl helmet",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Necklace of anguish",
      "Pegasian boots",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
    ],
  },
  {
    key: "crystal",
    label: "Crystal / Bowfa",
    tier: "late",
    combat: "range",
    items: [
      "Bow of faerdhinen (inactive)",
      "Crystal helm",
      "Crystal body",
      "Crystal legs",
      "Dragon arrow",
      "Necklace of anguish",
      "Pegasian boots",
    ],
  },
  {
    key: "blue-moon",
    label: "Blue moon",
    tier: "late",
    combat: "magic",
    items: [
      "Blue moon helm",
      "Blue moon chestplate",
      "Blue moon tassets",
      "Ancient sceptre",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
      "Elidinis' ward",
      "Eye of ayak (uncharged)",
    ],
  },
  {
    key: "end-slash",
    label: "Endgame Slash",
    tier: "end",
    combat: "melee",
    items: [
      "Blade of saeldor (inactive)",
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Ghrazi rapier",
      "Amulet of rancour",
      "Amulet of blood fury",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
      "Ferocious gloves",
      "Neitiznot faceguard",
    ],
  },
  {
    key: "end-crush",
    label: "Endgame Crush",
    tier: "end",
    combat: "melee",
    items: [
      "Inquisitor's great helm",
      "Inquisitor's hauberk",
      "Inquisitor's plateskirt",
      "Inquisitor's mace",
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Amulet of rancour",
      "Amulet of blood fury",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
      "Ferocious gloves",
    ],
  },
  {
    key: "end-stab",
    label: "Endgame Stab/Strength",
    tier: "end",
    combat: "melee",
    items: [
      "Ghrazi rapier",
      "Osmumten's fang",
      "Blade of saeldor (inactive)",
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Amulet of rancour",
      "Amulet of blood fury",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Avernic treads",
      "Primordial boots",
      "Ferocious gloves",
      "Neitiznot faceguard",
    ],
  },
  {
    key: "end-defence",
    label: "Endgame Defence",
    tier: "end",
    combat: "melee",
    items: [
      "Justiciar faceguard",
      "Justiciar chestguard",
      "Justiciar legguards",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Amulet of rancour",
      "Amulet of blood fury",
      "Primordial boots",
    ],
  },
  {
    key: "end-xbow",
    label: "Endgame Crossbow",
    tier: "end",
    combat: "range",
    items: [
      "Zaryte crossbow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Necklace of anguish",
      "Necklace of rupture",
      "Pegasian boots",
      "Venator ring",
      "Avernic treads",
    ],
  },
  {
    key: "end-blowpipe",
    label: "Endgame Blowpipe",
    tier: "end",
    combat: "range",
    items: [
      "Toxic blowpipe (empty)",
      "Dragon dart",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Necklace of anguish",
      "Necklace of rupture",
      "Venator ring",
      "Avernic treads",
      "Pegasian boots",
    ],
  },
  {
    key: "end-bow",
    label: "Endgame Bow",
    tier: "end",
    combat: "range",
    items: [
      "Twisted bow",
      "Venator bow (uncharged)",
      "Bow of faerdhinen (inactive)",
      "Dragon arrow",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Venator ring",
      "Necklace of anguish",
      "Necklace of rupture",
      "Avernic treads",
      "Pegasian boots",
    ],
  },
  {
    key: "end-ancients",
    label: "Endgame Ancients",
    tier: "end",
    combat: "magic",
    items: [
      "Virtus mask",
      "Virtus robe top",
      "Virtus robe bottom",
      "Kodai wand",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Tumeken's shadow (uncharged)",
      "Occult necklace",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
      "Eternal boots",
      "Tormented bracelet",
    ],
  },
  {
    key: "end-elemental",
    label: "Endgame Elemental",
    tier: "end",
    combat: "magic",
    items: [
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Harmonised nightmare staff",
      "Kodai wand",
      "Tumeken's shadow (uncharged)",
      "Occult necklace",
      "Tome of fire",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
      "Eternal boots",
      "Tormented bracelet",
    ],
  },
  {
    key: "end-demonbane",
    label: "Endgame Demonbane",
    tier: "end",
    combat: "magic",
    items: [
      "Purging staff",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Kodai wand",
      "Tumeken's shadow (uncharged)",
      "Occult necklace",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
      "Eternal boots",
      "Tormented bracelet",
    ],
  },
  {
    key: "end-megarare",
    label: "Endgame Megarare",
    tier: "end",
    items: [
      "Scythe of vitur (uncharged)",
      "Soulreaper axe",
      "Blade of saeldor (inactive)",
      "Ghrazi rapier",
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Amulet of rancour",
      "Ferocious gloves",
      "Primordial boots",
      "Twisted bow",
      "Zaryte crossbow",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Zaryte vambraces",
      "Venator ring",
      "Necklace of anguish",
      "Necklace of rupture",
      "Tumeken's shadow (uncharged)",
      "Harmonised nightmare staff",
      "Kodai wand",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Occult necklace",
      "Elidinis' ward (f)",
      "Confliction gauntlets",
      "Magus ring",
      "Avernic treads",
      "Eternal boots",
      "Tormented bracelet",
    ],
  },
  {
    key: "torva",
    label: "Torva",
    tier: "end",
    combat: "melee",
    items: [
      "Torva full helm",
      "Torva platebody",
      "Torva platelegs",
      "Ultor ring",
      "Amulet of rancour",
      "Primordial boots",
      "Ferocious gloves",
    ],
  },
  {
    key: "masori",
    label: "Masori",
    tier: "end",
    combat: "range",
    items: [
      "Masori mask",
      "Masori body",
      "Masori chaps",
      "Masori mask (f)",
      "Masori body (f)",
      "Masori chaps (f)",
      "Necklace of anguish",
      "Zaryte vambraces",
      "Pegasian boots",
    ],
  },
  {
    key: "ancestral",
    label: "Ancestral",
    tier: "end",
    combat: "magic",
    items: [
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Occult necklace",
      "Tormented bracelet",
      "Eternal boots",
    ],
  },
  {
    key: "oathplate",
    label: "Oathplate",
    tier: "end",
    combat: "melee",
    items: [
      "Oathplate helm",
      "Oathplate chest",
      "Oathplate legs",
    ],
  },
  {
    key: "3rd-age-melee",
    label: "3rd age melee",
    tier: "end",
    combat: "melee",
    items: [
      "3rd age full helmet",
      "3rd age platebody",
      "3rd age platelegs",
      "3rd age plateskirt",
      "3rd age kiteshield",
      "3rd age longsword",
    ],
  },
  {
    key: "3rd-age-range",
    label: "3rd age range",
    tier: "end",
    combat: "range",
    items: [
      "3rd age range coif",
      "3rd age range top",
      "3rd age range legs",
      "3rd age vambraces",
      "3rd age bow",
    ],
  },
  {
    key: "3rd-age-magic",
    label: "3rd age magic",
    tier: "end",
    combat: "magic",
    items: [
      "3rd age mage hat",
      "3rd age robe top",
      "3rd age robe",
      "3rd age amulet",
      "3rd age wand",
    ],
  },
];

export function gearSetsForTier(
  tier: string,
  combat: string,
): GearSetDef[] {
  if (tier === "all") return [];
  return GEAR_SETS.filter(
    (s) =>
      s.tier === tier &&
      (!s.combat || combat === "all" || s.combat === combat),
  );
}

export function gearSetItemNames(setKey: string): Set<string> | null {
  if (!setKey || setKey === "all") return null;
  const def = GEAR_SETS.find((s) => s.key === setKey);
  return def ? new Set(def.items) : null;
}
