/**
 * Primary offensive bonus used for Cost / bonus (efficiency) sorting.
 * - Melee items → Strength bonus
 * - Ranged items → Ranged Strength (ammo/weapons) or Ranged Strength from gear
 * - Magic items → Magic damage % (as integer percent points)
 *
 * Values are approximate / wiki-derived for tradeable catalog items.
 * Items with 0 are treated as no-bonus (sorted last on efficiency).
 */
export const OFFENSIVE_BONUS: Record<string, number> = {
  // ── Melee Strength ─────────────────────────────────────
  "Amulet of strength": 10,
  "Combat bracelet": 6,
  "Rune boots": 2,
  "Berserker helm": 3,
  "Dragon scimitar": 66,
  "Helm of neitiznot": 3,
  "Mixed hide cape": 1,
  "Dragon boots": 4,
  "Abyssal whip": 82,
  "Kraken tentacle": 4,
  "Amulet of fury": 8,
  "Zamorakian hasta": 85,
  "Zombie axe": 93,
  "Obsidian helmet": 3,
  "Obsidian platebody": 1,
  "Obsidian platelegs": 1,
  "Berserker necklace": 7,
  "Toktz-xil-ak": 49,
  "Toktz-xil-ek": 49,
  "Berserker ring": 8,
  "Ursine chainmace": 89,
  "Dharok's helm": 0,
  "Dharok's platebody": 0,
  "Dharok's platelegs": 0,
  "Dharok's greataxe": 105,
  "Guthan's helm": 0,
  "Guthan's platebody": 0,
  "Guthan's chainskirt": 0,
  "Guthan's warspear": 75,
  "Torag's helm": 0,
  "Torag's platebody": 0,
  "Torag's platelegs": 0,
  "Torag's hammers": 82,
  "Verac's helm": 0,
  "Verac's brassard": 0,
  "Verac's plateskirt": 0,
  "Verac's flail": 72,
  "Serpentine helm": 5,
  "Blood moon helm": 4,
  "Blood moon chestplate": 2,
  "Blood moon tassets": 2,
  "Dual macuahuitl": 80,
  "Amulet of torture": 10,
  "Bandos chestplate": 4,
  "Bandos tassets": 2,
  "Bandos boots": 0,
  "Primordial boots": 5,
  "Ferocious gloves": 14,
  "Neitiznot faceguard": 6,
  "Burning claws": 50,
  "Osmumten's fang": 105,
  "Abyssal bludgeon": 85,
  "Dragon warhammer": 95,
  "Bandos godsword": 132,
  "Dragon hunter lance": 85,
  "Voidwaker": 80,
  "Dragon claws": 56,
  "Noxious halberd": 100,
  "Ghrazi rapier": 89,
  "Justiciar faceguard": 0,
  "Justiciar chestguard": 0,
  "Justiciar legguards": 0,
  "Inquisitor's great helm": 4,
  "Inquisitor's hauberk": 4,
  "Inquisitor's plateskirt": 2,
  "Inquisitor's mace": 89,
  "Scythe of vitur (uncharged)": 75,
  "Soulreaper axe": 100,
  "Blade of saeldor (inactive)": 94,
  "Amulet of rancour": 12,
  "Amulet of blood fury": 8,
  "Torva full helm": 8,
  "Torva platebody": 6,
  "Torva platelegs": 4,
  "Ultor ring": 12,
  "Avernic treads": 5,

  // ── Ranged Strength ──────────────────────────────────
  "Maple shortbow": 0,
  "Adamant arrow": 31,
  "Magic shortbow": 0,
  "Rune arrow": 49,
  "Rune crossbow": 0,
  "Broad bolts": 100,
  "Diamond bolts (e)": 105,
  "Ruby bolts (e)": 103,
  "Dorgeshuun crossbow": 0,
  "Bone bolts": 49,
  "Amethyst arrow": 55,
  "Dragon crossbow": 0,
  "Toxic blowpipe (empty)": 40,
  "Adamant dart": 10,
  "Rune dart": 14,
  "Amethyst dart": 28,
  "Dragon dart": 20,
  "Red chinchompa": 15,
  "Black chinchompa": 30,
  "Twisted buckler": 0,
  "Odium ward": 0,
  "Antler guard": 0,
  "Eclipse atlatl": 0,
  "Atlatl dart": 0,
  "Eclipse moon helm": 0,
  "Eclipse moon chestplate": 0,
  "Eclipse moon tassets": 0,
  "Hunters' sunlight crossbow": 0,
  "Sunlight antler bolts": 0,
  "Moonlight antler bolts": 0,
  "Steel cannonball": 0,
  "Armadyl crossbow": 0,
  "Armadyl helmet": 0,
  "Armadyl chestplate": 0,
  "Armadyl chainskirt": 0,
  "Necklace of anguish": 5,
  "Pegasian boots": 0,
  "Dragon hunter crossbow": 0,
  "Dragonfire ward": 0,
  "Webweaver bow (u)": 65,
  "Scorching bow": 40,
  "Dragon arrow": 60,
  "Ruby dragon bolts (e)": 122,
  "Diamond dragon bolts (e)": 122,
  "Bow of faerdhinen (inactive)": 106,
  "Crystal helm": 0,
  "Crystal body": 0,
  "Crystal legs": 0,
  "Twisted bow": 20,
  "Zaryte crossbow": 0,
  "Venator bow (uncharged)": 25,
  "Masori mask": 2,
  "Masori body": 4,
  "Masori chaps": 2,
  "Masori mask (f)": 2,
  "Masori body (f)": 4,
  "Masori chaps (f)": 2,
  "Zaryte vambraces": 2,
  "Venator ring": 2,
  "Necklace of rupture": 8,

  // ── Magic damage % ───────────────────────────────────
  "Mystic hat (dark)": 0,
  "Mystic robe top (dark)": 0,
  "Mystic robe bottom (dark)": 0,
  "Mystic gloves (dark)": 0,
  "Mystic boots (dark)": 0,
  "Infinity hat": 0,
  "Infinity top": 0,
  "Infinity bottoms": 0,
  "Infinity gloves": 0,
  "Infinity boots": 0,
  "Bloodbark helm": 0,
  "Bloodbark body": 0,
  "Bloodbark legs": 0,
  "Bloodbark gauntlets": 0,
  "Bloodbark boots": 0,
  "Dagon'hai hat": 0,
  "Dagon'hai robe top": 0,
  "Dagon'hai robe bottom": 0,
  "Warped sceptre": 0,
  "Iban's staff (u)": 0,
  "Ahrim's hood": 0,
  "Ahrim's robetop": 0,
  "Ahrim's robeskirt": 0,
  "Ahrim's staff": 0,
  "Trident of the seas (full)": 0,
  "Uncharged trident": 0,
  "Uncharged toxic trident": 0,
  "Occult necklace": 5,
  "Seers ring": 0,
  "Mage's book": 0,
  "Tome of fire": 0,
  "Tome of water": 0,
  "Tome of earth": 0,
  "Blue moon helm": 0,
  "Blue moon chestplate": 0,
  "Blue moon tassets": 0,
  "Ancient sceptre": 0,
  "Toxic staff (uncharged)": 0,
  "Dragon hunter wand": 0,
  "Purging staff": 0,
  "Sanguinesti staff (uncharged)": 0,
  "Eye of ayak (uncharged)": 0,
  "Elidinis' ward": 0,
  "Elidinis' ward (f)": 5,
  "Eternal boots": 1,
  "Tormented bracelet": 5,
  "Virtus mask": 2,
  "Virtus robe top": 2,
  "Virtus robe bottom": 2,
  "Ancestral hat": 3,
  "Ancestral robe top": 3,
  "Ancestral robe bottom": 3,
  "Kodai wand": 15,
  "Harmonised nightmare staff": 0,
  "Tumeken's shadow (uncharged)": 0,
  "Confliction gauntlets": 0,
  "Magus ring": 2,
};

/** Returns the primary offensive bonus for efficiency sorting, or 0 if unknown / none. */
export function offensiveBonus(name: string): number {
  return OFFENSIVE_BONUS[name] ?? 0;
}

/**
 * Cost per unit of offensive bonus. Lower is better value.
 * Items with no bonus sort to the end (Infinity).
 */
export function costPerBonus(price: number, bonus: number): number {
  if (bonus <= 0 || price <= 0) return Number.POSITIVE_INFINITY;
  return price / bonus;
}
