import type { ActivityMethod } from "@/lib/activity-methods";

/** Wiki Hunter training tables. Red = no tick manip. Black = solo tick-manip. */
export const HUNTER_RATE_TABLES: ActivityMethod[] = [
  {
    id: "red-chins",
    label: "Red chinchompas (no tick manip)",
    skillKey: "hunter",
    level: 63,
    rateBands: [
      { level: 63, xpPerHour: 61_000 },
      { level: 70, xpPerHour: 72_000 },
      { level: 80, xpPerHour: 115_000 },
      { level: 90, xpPerHour: 136_000 },
      { level: 99, xpPerHour: 155_000 },
    ],
    consumables: [],
    rewards: [{ name: "Red chinchompa", expectedQtyPerHour: 585 }],
    intensity: "medium",
    notes: "Wiki no-tick red chin table (Tlati). Tick-manip is 85–220k. Qty/h at 99 = 155k/265.",
  },
  {
    id: "black-chins",
    label: "Black chinchompas (solo)",
    skillKey: "hunter",
    level: 73,
    rateBands: [
      { level: 73, xpPerHour: 145_000 },
      { level: 75, xpPerHour: 151_000 },
      { level: 80, xpPerHour: 167_000 },
      { level: 85, xpPerHour: 182_000 },
      { level: 90, xpPerHour: 197_000 },
      { level: 95, xpPerHour: 213_000 },
      { level: 99, xpPerHour: 225_000 },
    ],
    consumables: [],
    rewards: [{ name: "Black chinchompa", expectedQtyPerHour: 714 }],
    intensity: "high",
    notes: "Wiki solo black chin table (tick-manip). Alt column is 157–265k. Qty/h at 99 = 225k/315.",
  },
  {
    id: "herbiboar",
    label: "Herbiboar",
    skillKey: "hunter",
    level: 80,
    secondarySkill: "herblore",
    rateBands: [
      { level: 80, xpPerHour: 137_000, secondaryXpPerHour: 2_500 },
      { level: 85, xpPerHour: 147_000, secondaryXpPerHour: 2_700 },
      { level: 90, xpPerHour: 157_000, secondaryXpPerHour: 3_000 },
      { level: 95, xpPerHour: 166_000, secondaryXpPerHour: 3_150 },
      { level: 99, xpPerHour: 171_000, secondaryXpPerHour: 3_300 },
    ],
    consumables: [{ name: "Stamina potion(4)", qty: 7.5 }],
    rewards: [
      { name: "Grimy guam leaf", expectedQtyPerHour: 34.5 },
      { name: "Grimy ranarr weed", expectedQtyPerHour: 14.76 },
      { name: "Grimy irit leaf", expectedQtyPerHour: 13.26 },
      { name: "Grimy avantoe", expectedQtyPerHour: 14.94 },
      { name: "Grimy kwuarm", expectedQtyPerHour: 19.62 },
      { name: "Grimy snapdragon", expectedQtyPerHour: 12.42 },
      { name: "Grimy cadantine", expectedQtyPerHour: 20.46 },
      { name: "Grimy lantadyme", expectedQtyPerHour: 19.62 },
      { name: "Grimy dwarf weed", expectedQtyPerHour: 16.86 },
      { name: "Grimy torstol", expectedQtyPerHour: 13.56 },
      { name: "Numulite", expectedQtyPerHour: 802 },
    ],
    intensity: "medium",
    notes: "Wiki herbiboar XP/h table. Herb list is MMG at 99 Herblore.",
  },
  {
    id: "letvek",
    label: "Letvek (Vampyrium box traps)",
    skillKey: "hunter",
    level: 76,
    rateBands: [
      { level: 76, xpPerHour: 95_000 },
      { level: 80, xpPerHour: 106_000 },
      { level: 99, xpPerHour: 115_000 },
    ],
    consumables: [],
    rewards: [{ name: "Letvek", expectedQtyPerHour: 520 }],
    intensity: "medium",
    notes:
      "Blood Moon Rises / Vampyrium. 208.5 XP per catch. Community ~500–550 bait/hr; lazy box-reset ~104k at 99. Bait for Stymphikes.",
  },
  {
    id: "stymphike",
    label: "Stymphike (Vampyrium)",
    skillKey: "hunter",
    level: 82,
    rateBands: [
      { level: 82, xpPerHour: 120_000 },
      { level: 85, xpPerHour: 130_000 },
      { level: 86, xpPerHour: 140_000 },
      { level: 99, xpPerHour: 143_000 },
    ],
    consumables: [{ name: "Letvek", qty: 90 }],
    rewards: [{ name: "Stymphike feather", expectedQtyPerHour: 1_335 }],
    intensity: "low",
    notes:
      "Blood Moon Rises / Vampyrium. 1,350 XP per spear. Wiki XP table; 15 feathers/catch. Hide-in-bush auto-spear is AFK; click the bird for slightly better uptime. ~1 Letvek per catch (sometimes 2–3). Feathers turn in for limited off-task Venators.",
  },
];
