/** Wiki PNG used when a method has no priced output to steal an icon from. */

export const SKILL_ICONS: Record<string, string> = {
  agility: "Agility_icon.png",
  construction: "Construction_icon.png",
  cooking: "Cooking_icon.png",
  crafting: "Crafting_icon.png",
  farming: "Farming_icon.png",
  firemaking: "Firemaking_icon.png",
  fishing: "Fishing_icon.png",
  fletching: "Fletching_icon.png",
  herblore: "Herblore_icon.png",
  hunter: "Hunter_icon.png",
  magic: "Magic_icon.png",
  mining: "Mining_icon.png",
  prayer: "Prayer_icon.png",
  runecraft: "Runecraft_icon.png",
  sailing: "Sailing_icon.png",
  smithing: "Smithing_icon.png",
  thieving: "Thieving_icon.png",
  woodcutting: "Woodcutting_icon.png",
};

/** Exact wiki filenames for XP-only / activity rows. */
export const METHOD_ICONS: Record<string, string> = {
  "varrock-rooftop": "Mark_of_grace.png",
  "canifis-rooftop": "Mark_of_grace.png",
  "falador-rooftop": "Mark_of_grace.png",
  "seers-rooftop": "Mark_of_grace.png",
  "pollnivneach-rooftop": "Mark_of_grace.png",
  "relekka-rooftop": "Mark_of_grace.png",
  "ardougne-rooftop": "Mark_of_grace.png",
  "colossal-wyrm-basic": "Colossal_Wyrm_Agility_Course.png",
  "colossal-wyrm-advanced": "Colossal_Wyrm_Agility_Course.png",
  "wilderness-agility": "Agility_arena_ticket.png",
  "wilderness-agility-tickets": "Agility_arena_ticket.png",
  werewolf: "Agility_arena_ticket.png",
  prifddinas: "Crystal_shard.png",
  "ape-atoll": "Agility_icon.png",
  "dorgesh-kaan": "Agility_icon.png",
  "hallowed-sepulchre": "Hallowed_mark_5.png",
  "sepulchre-floor-3": "Hallowed_mark_5.png",
  "sepulchre-floor-4": "Hallowed_mark_5.png",
  "sepulchre-floor-5-loot": "Hallowed_mark_5.png",
  "brimhaven-arena": "Agility_arena_ticket.png",
  "agility-pyramid": "Pyramid_top.png",

  sandstone: "Sandstone_(10kg).png",
  granite: "Granite_(5kg).png",
  "granite-3tick": "Granite_(5kg).png",
  "motherlode-mine": "Pay-dirt.png",
  "volcanic-mine": "Volcanic_ash.png",
  "blast-mine": "Dynamite.png",
  "shooting-stars": "Stardust_1.png",
  "infernal-shale-afk": "Crushed_infernal_shale.png",
  "infernal-shale-rocks": "Crushed_infernal_shale.png",
  "infernal-shale": "Crushed_infernal_shale.png",

  "wintertodt-mass": "Burning_log.png",
  "tempoross-mass-cook": "Raw_harpoonfish.png",
  "gotr-mass": "Abyssal_pearls.png",
  "giants-foundry": "Cannonball.png",
  "mahogany-homes": "Plank.png",
  "pyramid-plunder": "Pharaoh's_sceptre.png",
  "stealing-artefacts": "Artefact.png",
  "mta-enchanting": "Bones_to_peaches.png",
  herbiboar: "Herbi.png",
  "mastering-mixology": "Reagent_pouch.png",
  "tithe-farm": "Grape_seed.png",
  "farming-contracts": "Seed_pack.png",
  hespori: "Bottomless_compost_bucket.png",
  "forestry-events": "Anima-infused_bark.png",
  "hunter-rumours": "Hunter_icon.png",
  "hunter-implings": "Magpie_impling_jar.png",
  "rainbow-crabs": "Rainbow_crab_paste.png",
  "rainbow-crabs-4trap": "Rainbow_crab_paste.png",
  "spotted-kebbit": "Spotted_kebbit_fur.png",
  "dark-kebbit": "Dark_kebbit_fur.png",
  "dashing-kebbit": "Dashing_kebbit_fur.png",

  "courier-early": "Sailing_icon.png",
  "sea-charting": "Sailing_icon.png",
  "courier-summer-shore": "Sailing_icon.png",
  "courier-rellekka": "Sailing_icon.png",
  "courier-prifddinas": "Sailing_icon.png",
  leechfin: "Leaping_trout.png",

  "oak-larder": "Oak_plank.png",
  "oak-dining-table": "Oak_plank.png",
  "teak-armchair": "Teak_plank.png",
  "mythical-cape": "Mythical_cape.png",
  "mahogany-table": "Mahogany_plank.png",
  "teak-garden-bench": "Teak_plank.png",
  "oak-door": "Oak_plank.png",
  "mahogany-gnome-bench": "Mahogany_plank.png",
  "teak-larder": "Teak_plank.png",
  "teak-table": "Teak_plank.png",
  "demonic-throne": "Magic_stone.png",
  "marble-cape-rack": "Marble_block.png",
};

export function methodFallbackIcon(id: string, skillKey?: string): string | null {
  if (METHOD_ICONS[id]) return METHOD_ICONS[id];
  if (skillKey && SKILL_ICONS[skillKey]) return SKILL_ICONS[skillKey];
  return null;
}
