import type { ActivityMethod } from "@/lib/activity-methods";

export const MINING_RATE_TABLES: ActivityMethod[] = [
  {
    id: "iron-ore",
    label: "Iron ore",
    skillKey: "mining",
    level: 15,
    rateBands: [
      { level: 15, xpPerHour: 50_000 },
      { level: 60, xpPerHour: 75_000 },
    ],
    consumables: [],
    rewards: [{ name: "Iron ore", expectedQtyPerHour: 2143 }],
    intensity: "high",
    notes: "Wiki iron: 45–55k below 60, 70–80k from 60 (Mining Guild + Varrock armour). Mid of each band. Qty at 60 = 75k/35.",
  },
  {
    id: "gem-rock",
    label: "Gem rocks (no 3-tick)",
    skillKey: "mining",
    level: 40,
    rateBands: [
      { level: 40, xpPerHour: 40_000 },
      { level: 50, xpPerHour: 46_000 },
      { level: 60, xpPerHour: 52_000 },
      { level: 70, xpPerHour: 58_000 },
      { level: 80, xpPerHour: 66_000 },
      { level: 90, xpPerHour: 70_000 },
      { level: 99, xpPerHour: 75_000 },
    ],
    consumables: [],
    rewards: [
      { name: "Uncut opal", expectedQtyPerHour: 540 },
      { name: "Uncut jade", expectedQtyPerHour: 270 },
      { name: "Uncut red topaz", expectedQtyPerHour: 135 },
      { name: "Uncut sapphire", expectedQtyPerHour: 81 },
      { name: "Uncut emerald", expectedQtyPerHour: 45 },
      { name: "Uncut ruby", expectedQtyPerHour: 45 },
      { name: "Uncut diamond", expectedQtyPerHour: 36 },
    ],
    intensity: "high",
    notes: "Wiki gem-rock no-tick table. 3-tick is 89–110k. Gem mix ≈ 99 rate × wiki 128-table.",
  },
  {
    id: "granite-3tick",
    label: "Granite (3-tick)",
    skillKey: "mining",
    level: 45,
    rateBands: [
      { level: 45, xpPerHour: 87_000 },
      { level: 55, xpPerHour: 95_000 },
      { level: 65, xpPerHour: 103_000 },
      { level: 75, xpPerHour: 109_000 },
      { level: 85, xpPerHour: 114_000 },
      { level: 95, xpPerHour: 119_000 },
      { level: 99, xpPerHour: 126_000 },
    ],
    consumables: [],
    rewards: [],
    intensity: "high",
    notes: "Wiki 3-tick granite table. Power-mine (no granite sold).",
  },
  {
    id: "amethyst",
    label: "Amethyst",
    skillKey: "mining",
    level: 92,
    rateBands: [
      { level: 92, xpPerHour: 20_000 },
      { level: 99, xpPerHour: 25_000 },
    ],
    consumables: [],
    rewards: [{ name: "Amethyst", expectedQtyPerHour: 104 }],
    intensity: "low",
    notes: "Wiki 20–25k amethyst band. Qty at 99 = 25k/240.",
  },
];
