import type { ActivityMethod } from "@/lib/activity-methods";

export const MINING_RATE_TABLES: ActivityMethod[] = [
  {
    id: "iron-ore",
    label: "Iron ore",
    skillKey: "mining",
    level: 15,
    rateBands: [
      { level: 15, xpPerHour: 50_000 },
      { level: 60, xpPerHour: 75_000 },
    ],
    consumables: [],
    rewards: [{ name: "Iron ore", expectedQtyPerHour: 2143 }],
    intensity: "high",
    notes: "Wiki iron: 45–55k below 60, 70–80k from 60 (Mining Guild + Varrock armour). Mid of each band. Qty at 60 = 75k/35.",
  },
  {
    id: "gem-rock",
    label: "Gem rocks (no 3-tick)",
    skillKey: "mining",
    level: 40,
    rateBands: [
      { level: 40, xpPerHour: 40_000 },
      { level: 50, xpPerHour: 46_000 },
      { level: 60, xpPerHour: 52_000 },
      { level: 70, xpPerHour: 58_000 },
      { level: 80, xpPerHour: 66_000 },
      { level: 90, xpPerHour: 70_000 },
      { level: 99, xpPerHour: 75_000 },
    ],
    consumables: [],
    rewards: [
      { name: "Uncut opal", expectedQtyPerHour: 540 },
      { name: "Uncut jade", expectedQtyPerHour: 270 },
      { name: "Uncut red topaz", expectedQtyPerHour: 135 },
      { name: "Uncut sapphire", expectedQtyPerHour: 81 },
      { name: "Uncut emerald", expectedQtyPerHour: 45 },
      { name: "Uncut ruby", expectedQtyPerHour: 45 },
      { name: "Uncut diamond", expectedQtyPerHour: 36 },
    ],
    intensity: "high",
    notes: "Wiki gem-rock no-tick table. 3-tick is 89–110k. Gem mix ≈ 99 rate × wiki 128-table.",
  },
  {
    id: "granite-3tick",
    label: "Granite (3-tick)",
    skillKey: "mining",
    level: 45,
    rateBands: [
      { level: 45, xpPerHour: 87_000 },
      { level: 55, xpPerHour: 95_000 },
      { level: 65, xpPerHour: 103_000 },
      { level: 75, xpPerHour: 109_000 },
      { level: 85, xpPerHour: 114_000 },
      { level: 95, xpPerHour: 119_000 },
      { level: 99, xpPerHour: 126_000 },
    ],
    consumables: [],
    rewards: [],
    intensity: "high",
    notes: "Wiki 3-tick granite table. Power-mine (no granite sold).",
  },
  {
    id: "amethyst",
    label: "Amethyst",
    skillKey: "mining",
    level: 92,
    rateBands: [
      { level: 92, xpPerHour: 20_000 },
      { level: 99, xpPerHour: 25_000 },
    ],
    consumables: [],
    rewards: [{ name: "Amethyst", expectedQtyPerHour: 104 }],
    intensity: "low",
    notes: "Wiki 20–25k amethyst band. Qty at 99 = 25k/240.",
  },
  {
    id: "infernal-shale-afk",
    label: "Infernal shale (AFK deposit)",
    skillKey: "mining",
    level: 78,
    rateBands: [{ level: 78, xpPerHour: 9_860 }],
    consumables: [],
    rewards: [{ name: "Crushed infernal shale", expectedQtyPerHour: 221 }],
    intensity: "low",
    notes:
      "Wiki MMG deposit: 140–200 shale/h → ~180–260 crushed (1.3 crush ratio). Results table 221 crushed, 9,860 XP. Chasm of Fire, A Kingdom Divided, 78 Mining.",
  },
  {
    id: "infernal-shale-rocks",
    label: "Infernal shale (rocks)",
    skillKey: "mining",
    level: 78,
    rateBands: [{ level: 78, xpPerHour: 35_960 }],
    consumables: [],
    rewards: [{ name: "Crushed infernal shale", expectedQtyPerHour: 806 }],
    intensity: "medium",
    notes:
      "Wiki MMG rocks (medium intensity). Results table 806 crushed, 35,960 XP. Mine rocks then crush with hammer + chisel.",
  },
  {
    id: "infernal-shale",
    label: "Infernal shale (tick manip)",
    skillKey: "mining",
    level: 78,
    rateBands: [{ level: 78, xpPerHour: 68_368 }],
    consumables: [],
    rewards: [{ name: "Crushed infernal shale", expectedQtyPerHour: 2080 }],
    intensity: "high",
    notes:
      "Wiki MMG tick manipulation (Jim's wet cloth). Results table 2,080 crushed, 68,368 XP. Realistic 1,500–1,700 shale mined / 1,900–2,200 crushed.",
  },
];
