export type CatalogItem = {
  name: string;
  /** Filter tags for subset navigation. */
  tags: string[];
};

export type CatalogGroup = {
  id: string;
  label: string;
  kind: "gear" | "skilling";
  note: string;
  items: CatalogItem[];
};

/**
 * Gear tiers follow the wiki progression guides:
 * - https://oldschool.runescape.wiki/w/Guide:Melee_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Ranged_Gear_Progression
 * - https://oldschool.runescape.wiki/w/Guide:Magic_Gear_Progression
 * Only tradeable GE items (exact wiki names). Untradeables omitted.
 *
 * Consumable ammo (arrows, bolts, darts, chinchompas, cannonballs) and
 * charge materials (Zulrah's scales, revenant ether) live under utility
 * with the "supplies" tag — not under ranged/melee gear progression.
 */
export const CATALOG: CatalogGroup[] = [
  {
    id: "melee",
    label: "Melee gear",
    kind: "gear",
    note: "Melee progression milestones",
    items: [
      { name: "Amulet of strength", tags: ["melee", "neck", "early"] },
      { name: "Combat bracelet", tags: ["melee", "hands", "early"] },
      { name: "Rune boots", tags: ["melee", "feet", "early"] },
      { name: "Berserker helm", tags: ["melee", "head", "early"] },
      { name: "Dragon scimitar", tags: ["melee", "weapon", "one-handed", "early"] },
      { name: "Helm of neitiznot", tags: ["melee", "head", "early", "mid"] },
      { name: "Mixed hide cape", tags: ["melee", "cape", "early"] },
      { name: "Dragon boots", tags: ["melee", "feet", "early", "mid"] },
      { name: "Abyssal whip", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Kraken tentacle", tags: ["melee", "weapon", "one-handed", "mid", "late"] },
      { name: "Amulet of fury", tags: ["melee", "neck", "mid"] },
      { name: "Zamorakian hasta", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Zombie axe", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Obsidian helmet", tags: ["melee", "head", "mid"] },
      { name: "Obsidian platebody", tags: ["melee", "chest", "mid"] },
      { name: "Obsidian platelegs", tags: ["melee", "legs", "mid"] },
      { name: "Berserker necklace", tags: ["melee", "neck", "mid"] },
      { name: "Toktz-xil-ak", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Toktz-xil-ek", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Berserker ring", tags: ["melee", "ring", "mid", "late"] },
      { name: "Ursine chainmace", tags: ["melee", "weapon", "one-handed", "mid", "late"] },
      { name: "Dharok's helm", tags: ["melee", "head", "mid"] },
      { name: "Dharok's platebody", tags: ["melee", "chest", "mid"] },
      { name: "Dharok's platelegs", tags: ["melee", "legs", "mid"] },
      { name: "Dharok's greataxe", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Guthan's helm", tags: ["melee", "head", "mid"] },
      { name: "Guthan's platebody", tags: ["melee", "chest", "mid"] },
      { name: "Guthan's chainskirt", tags: ["melee", "legs", "mid"] },
      { name: "Guthan's warspear", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Torag's helm", tags: ["melee", "head", "mid"] },
      { name: "Torag's platebody", tags: ["melee", "chest", "mid"] },
      { name: "Torag's platelegs", tags: ["melee", "legs", "mid"] },
      { name: "Torag's hammers", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Verac's helm", tags: ["melee", "head", "mid"] },
      { name: "Verac's brassard", tags: ["melee", "chest", "mid"] },
      { name: "Verac's plateskirt", tags: ["melee", "legs", "mid"] },
      { name: "Verac's flail", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Karil's coif", tags: ["melee", "head", "mid"] },
      { name: "Ahrim's hood", tags: ["melee", "head", "mid"] },
      { name: "Serpentine helm", tags: ["melee", "head", "late"] },
      { name: "Blood moon helm", tags: ["melee", "head", "mid", "late"] },
      { name: "Blood moon chestplate", tags: ["melee", "chest", "mid", "late"] },
      { name: "Blood moon tassets", tags: ["melee", "legs", "mid", "late"] },
      { name: "Dual macuahuitl", tags: ["melee", "weapon", "two-handed", "mid", "late"] },
      { name: "Amulet of torture", tags: ["melee", "neck", "late"] },
      { name: "Bandos chestplate", tags: ["melee", "chest", "late"] },
      { name: "Bandos tassets", tags: ["melee", "legs", "late"] },
      { name: "Bandos boots", tags: ["melee", "feet", "late"] },
      { name: "Primordial boots", tags: ["melee", "feet", "late", "end"] },
      { name: "Ferocious gloves", tags: ["melee", "hands", "late"] },
      { name: "Neitiznot faceguard", tags: ["melee", "head", "late"] },
      { name: "Burning claws", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Osmumten's fang", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Abyssal bludgeon", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Dragon warhammer", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Bandos godsword", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Dragon hunter lance", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Voidwaker", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Dragon claws", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Noxious halberd", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Ghrazi rapier", tags: ["melee", "weapon", "one-handed", "late", "end"] },
      { name: "Justiciar faceguard", tags: ["melee", "head", "end"] },
      { name: "Justiciar chestguard", tags: ["melee", "chest", "end"] },
      { name: "Justiciar legguards", tags: ["melee", "legs", "end"] },
      { name: "Inquisitor's great helm", tags: ["melee", "head", "end"] },
      { name: "Inquisitor's hauberk", tags: ["melee", "chest", "end"] },
      { name: "Inquisitor's plateskirt", tags: ["melee", "legs", "end"] },
      { name: "Inquisitor's mace", tags: ["melee", "weapon", "one-handed", "end"] },
      { name: "Scythe of vitur (uncharged)", tags: ["melee", "weapon", "two-handed", "end"] },
      { name: "Soulreaper axe", tags: ["melee", "weapon", "two-handed", "end"] },
      { name: "Blade of saeldor (inactive)", tags: ["melee", "weapon", "one-handed", "end"] },
      { name: "Amulet of rancour", tags: ["melee", "neck", "end"] },
      { name: "Amulet of blood fury", tags: ["melee", "neck", "end"] },
      { name: "Torva full helm", tags: ["melee", "head", "end"] },
      { name: "Torva platebody", tags: ["melee", "chest", "end"] },
      { name: "Torva platelegs", tags: ["melee", "legs", "end"] },
      { name: "Ultor ring", tags: ["melee", "ring", "end"] },
      { name: "Avernic treads", tags: ["melee", "feet", "end"] },
    ],
  },
  {
    id: "ranged",
    label: "Ranged gear",
    kind: "gear",
    note: "Ranged progression milestones",
    items: [
      { name: "Maple shortbow", tags: ["range", "weapon", "two-handed", "early"] },
      { name: "Magic shortbow", tags: ["range", "weapon", "two-handed", "early", "mid"] },
      { name: "Rune crossbow", tags: ["range", "weapon", "one-handed", "early", "mid"] },
      { name: "Dorgeshuun crossbow", tags: ["range", "weapon", "one-handed", "early"] },
      { name: "Dragon crossbow", tags: ["range", "weapon", "one-handed", "mid", "late"] },
      { name: "Toxic blowpipe (empty)", tags: ["range", "weapon", "two-handed", "mid", "late"] },
      { name: "Twisted buckler", tags: ["range", "shield", "late"] },
      { name: "Odium ward", tags: ["range", "shield", "mid", "late"] },
      { name: "Antler guard", tags: ["range", "shield", "mid"] },
      { name: "Eclipse atlatl", tags: ["range", "weapon", "one-handed", "mid", "late"] },
      { name: "Eclipse moon helm", tags: ["range", "head", "mid", "late"] },
      { name: "Eclipse moon chestplate", tags: ["range", "chest", "mid", "late"] },
      { name: "Eclipse moon tassets", tags: ["range", "legs", "mid", "late"] },
      { name: "Hunters' sunlight crossbow", tags: ["range", "weapon", "one-handed", "mid"] },
      { name: "Armadyl crossbow", tags: ["range", "weapon", "one-handed", "late"] },
      { name: "Armadyl helmet", tags: ["range", "head", "late"] },
      { name: "Armadyl chestplate", tags: ["range", "chest", "late"] },
      { name: "Armadyl chainskirt", tags: ["range", "legs", "late"] },
      { name: "Necklace of anguish", tags: ["range", "neck", "late", "end"] },
      { name: "Pegasian boots", tags: ["range", "feet", "late", "end"] },
      { name: "Dragon hunter crossbow", tags: ["range", "weapon", "one-handed", "late"] },
      { name: "Dragonfire ward", tags: ["range", "shield", "late"] },
      { name: "Webweaver bow (u)", tags: ["range", "weapon", "two-handed", "late"] },
      { name: "Scorching bow", tags: ["range", "weapon", "two-handed", "late"] },
      { name: "Bow of faerdhinen (inactive)", tags: ["range", "weapon", "two-handed", "late", "end"] },
      { name: "Crystal helm", tags: ["range", "head", "late"] },
      { name: "Crystal body", tags: ["range", "chest", "late"] },
      { name: "Crystal legs", tags: ["range", "legs", "late"] },
      { name: "Twisted bow", tags: ["range", "weapon", "two-handed", "end"] },
      { name: "Zaryte crossbow", tags: ["range", "weapon", "one-handed", "end"] },
      { name: "Venator bow (uncharged)", tags: ["range", "weapon", "two-handed", "end"] },
      { name: "Masori mask", tags: ["range", "head", "end"] },
      { name: "Masori body", tags: ["range", "chest", "end"] },
      { name: "Masori chaps", tags: ["range", "legs", "end"] },
      { name: "Masori mask (f)", tags: ["range", "head", "end"] },
      { name: "Masori body (f)", tags: ["range", "chest", "end"] },
      { name: "Masori chaps (f)", tags: ["range", "legs", "end"] },
      { name: "Zaryte vambraces", tags: ["range", "hands", "end"] },
      { name: "Venator ring", tags: ["range", "ring", "end"] },
      { name: "Necklace of rupture", tags: ["range", "neck", "end"] },
      { name: "Avernic treads", tags: ["range", "feet", "end"] },
    ],
  },
  {
    id: "magic",
    label: "Magic gear",
    kind: "gear",
    note: "Magic progression milestones",
    items: [
      { name: "Mystic hat (dark)", tags: ["magic", "head", "early"] },
      { name: "Mystic robe top (dark)", tags: ["magic", "chest", "early"] },
      { name: "Mystic robe bottom (dark)", tags: ["magic", "legs", "early"] },
      { name: "Mystic gloves (dark)", tags: ["magic", "hands", "early"] },
      { name: "Mystic boots (dark)", tags: ["magic", "feet", "early"] },
      { name: "Infinity hat", tags: ["magic", "head", "mid"] },
      { name: "Infinity top", tags: ["magic", "chest", "mid"] },
      { name: "Infinity bottoms", tags: ["magic", "legs", "mid"] },
      { name: "Infinity gloves", tags: ["magic", "hands", "mid"] },
      { name: "Infinity boots", tags: ["magic", "feet", "mid"] },
      { name: "Bloodbark helm", tags: ["magic", "head", "mid"] },
      { name: "Bloodbark body", tags: ["magic", "chest", "mid"] },
      { name: "Bloodbark legs", tags: ["magic", "legs", "mid"] },
      { name: "Bloodbark gauntlets", tags: ["magic", "hands", "mid"] },
      { name: "Bloodbark boots", tags: ["magic", "feet", "mid"] },
      { name: "Dagon'hai hat", tags: ["magic", "head", "mid"] },
      { name: "Dagon'hai robe top", tags: ["magic", "chest", "mid"] },
      { name: "Dagon'hai robe bottom", tags: ["magic", "legs", "mid"] },
      { name: "Warped sceptre", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Iban's staff (u)", tags: ["magic", "weapon", "two-handed", "early", "mid"] },
      { name: "Ahrim's hood", tags: ["magic", "head", "mid"] },
      { name: "Ahrim's robetop", tags: ["magic", "chest", "mid"] },
      { name: "Ahrim's robeskirt", tags: ["magic", "legs", "mid"] },
      { name: "Ahrim's staff", tags: ["magic", "weapon", "two-handed", "mid"] },
      { name: "Trident of the seas (full)", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Uncharged trident", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Uncharged toxic trident", tags: ["magic", "weapon", "one-handed", "mid", "late"] },
      { name: "Occult necklace", tags: ["magic", "neck", "mid", "late"] },
      { name: "Seers ring", tags: ["magic", "ring", "mid", "late"] },
      { name: "Mage's book", tags: ["magic", "shield", "mid", "late"] },
      { name: "Tome of fire", tags: ["magic", "shield", "mid", "late"] },
      { name: "Tome of water", tags: ["magic", "shield", "mid", "late"] },
      { name: "Tome of earth", tags: ["magic", "shield", "mid", "late"] },
      { name: "Blue moon helm", tags: ["magic", "head", "mid", "late"] },
      { name: "Blue moon chestplate", tags: ["magic", "chest", "mid", "late"] },
      { name: "Blue moon tassets", tags: ["magic", "legs", "mid", "late"] },
      { name: "Ancient sceptre", tags: ["magic", "weapon", "one-handed", "mid", "late"] },
      { name: "Toxic staff (uncharged)", tags: ["magic", "weapon", "two-handed", "late"] },
      { name: "Dragon hunter wand", tags: ["magic", "weapon", "one-handed", "late"] },
      { name: "Purging staff", tags: ["magic", "weapon", "two-handed", "late"] },
      { name: "Sanguinesti staff (uncharged)", tags: ["magic", "weapon", "one-handed", "late"] },
      { name: "Eye of ayak (uncharged)", tags: ["magic", "weapon", "one-handed", "late"] },
      { name: "Elidinis' ward", tags: ["magic", "shield", "late"] },
      { name: "Elidinis' ward (f)", tags: ["magic", "shield", "end"] },
      { name: "Eternal boots", tags: ["magic", "feet", "late", "end"] },
      { name: "Tormented bracelet", tags: ["magic", "hands", "late", "end"] },
      { name: "Virtus mask", tags: ["magic", "head", "late", "end"] },
      { name: "Virtus robe top", tags: ["magic", "chest", "late", "end"] },
      { name: "Virtus robe bottom", tags: ["magic", "legs", "late", "end"] },
      { name: "Ancestral hat", tags: ["magic", "head", "end"] },
      { name: "Ancestral robe top", tags: ["magic", "chest", "end"] },
      { name: "Ancestral robe bottom", tags: ["magic", "legs", "end"] },
      { name: "Kodai wand", tags: ["magic", "weapon", "one-handed", "end"] },
      { name: "Harmonised nightmare staff", tags: ["magic", "weapon", "two-handed", "end"] },
      { name: "Tumeken's shadow (uncharged)", tags: ["magic", "weapon", "two-handed", "end"] },
      { name: "Confliction gauntlets", tags: ["magic", "hands", "end"] },
      { name: "Magus ring", tags: ["magic", "ring", "end"] },
      { name: "Avernic treads", tags: ["magic", "feet", "end"] },
    ],
  },
  {
    id: "utility",
    label: "Utility & supplies",
    kind: "gear",
    note: "Consumables, ammo, and everyday kit",
    items: [
      { name: "Saradomin brew(4)", tags: ["supplies", "potion"] },
      { name: "Zamorak brew(4)", tags: ["supplies", "potion"] },
      { name: "Ancient brew(4)", tags: ["supplies", "potion"] },
      { name: "Forgotten brew(4)", tags: ["supplies", "potion"] },
      { name: "Super restore(4)", tags: ["supplies", "potion"] },
      { name: "Prayer potion(4)", tags: ["supplies", "potion"] },
      { name: "Sanfew serum(4)", tags: ["supplies", "potion"] },
      { name: "Menaphite remedy(4)", tags: ["supplies", "potion"] },
      { name: "Ranging potion(4)", tags: ["supplies", "potion"] },
      { name: "Magic potion(4)", tags: ["supplies", "potion"] },
      { name: "Bastion potion(4)", tags: ["supplies", "potion"] },
      { name: "Battlemage potion(4)", tags: ["supplies", "potion"] },
      { name: "Super combat potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine super combat potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine bastion potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine magic potion(4)", tags: ["supplies", "potion"] },
      { name: "Stamina potion(4)", tags: ["supplies", "potion"] },
      { name: "Extended stamina potion(4)", tags: ["supplies", "potion"] },
      { name: "Extended antifire(4)", tags: ["supplies", "potion"] },
      { name: "Extended super antifire(4)", tags: ["supplies", "potion"] },
      { name: "Anti-venom+(4)", tags: ["supplies", "potion"] },
      { name: "Guthix rest(4)", tags: ["supplies", "potion"] },
      { name: "Saturated heart", tags: ["supplies", "potion"] },
      { name: "Anglerfish", tags: ["supplies", "food"] },
      { name: "Shark", tags: ["supplies", "food"] },
      { name: "Manta ray", tags: ["supplies", "food"] },
      { name: "Dark crab", tags: ["supplies", "food"] },
      { name: "Marlin", tags: ["supplies", "food"] },
      { name: "Halibut", tags: ["supplies", "food"] },
      { name: "Haddock", tags: ["supplies", "food"] },
      { name: "Cooked karambwan", tags: ["supplies", "food"] },
      { name: "Blighted karambwan", tags: ["supplies", "food"] },
      { name: "Cooked moonlight antelope", tags: ["supplies", "food"] },
      { name: "Cooked dashing kebbit", tags: ["supplies", "food"] },
      { name: "Amulet of glory(6)", tags: ["supplies", "neck"] },
      { name: "Zulrah's scales", tags: ["supplies"] },
      { name: "Revenant ether", tags: ["supplies"] },
      { name: "Adamant arrow", tags: ["supplies", "ammo"] },
      { name: "Rune arrow", tags: ["supplies", "ammo"] },
      { name: "Amethyst arrow", tags: ["supplies", "ammo"] },
      { name: "Dragon arrow", tags: ["supplies", "ammo"] },
      { name: "Bone bolts", tags: ["supplies", "ammo"] },
      { name: "Broad bolts", tags: ["supplies", "ammo"] },
      { name: "Diamond bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Ruby bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Sunlight antler bolts", tags: ["supplies", "ammo"] },
      { name: "Moonlight antler bolts", tags: ["supplies", "ammo"] },
      { name: "Ruby dragon bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Diamond dragon bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Adamant dart", tags: ["supplies", "ammo"] },
      { name: "Rune dart", tags: ["supplies", "ammo"] },
      { name: "Amethyst dart", tags: ["supplies", "ammo"] },
      { name: "Dragon dart", tags: ["supplies", "ammo"] },
      { name: "Atlatl dart", tags: ["supplies", "ammo"] },
      { name: "Red chinchompa", tags: ["supplies", "ammo"] },
      { name: "Black chinchompa", tags: ["supplies", "ammo"] },
      { name: "Steel cannonball", tags: ["supplies", "ammo"] },
    ],
  },
  {
    id: "herblore",
    label: "Herblore",
    kind: "skilling",
    note: "Wiki-recommended potion training (unf + secondary)",
    items: [
      { name: "Grimy ranarr weed", tags: ["herblore"] },
      { name: "Ranarr weed", tags: ["herblore"] },
      { name: "Snapdragon", tags: ["herblore"] },
      { name: "Toadflax", tags: ["herblore"] },
      { name: "Torstol", tags: ["herblore"] },
      { name: "Kwuarm", tags: ["herblore"] },
      { name: "Cadantine", tags: ["herblore"] },
      { name: "Lantadyme", tags: ["herblore"] },
      { name: "Dwarf weed", tags: ["herblore"] },
      { name: "Snape grass", tags: ["herblore"] },
      { name: "Crushed nest", tags: ["herblore"] },
      { name: "Wine of zamorak", tags: ["herblore"] },
      { name: "Vial of water", tags: ["herblore"] },
      { name: "Amylase crystal", tags: ["herblore"] },
    ],
  },
  {
    id: "construction",
    label: "Construction",
    kind: "skilling",
    note: "POH tables/benches/doors, mythical capes, hull parts & repair kits",
    items: [
      { name: "Oak plank", tags: ["construction"] },
      { name: "Teak plank", tags: ["construction"] },
      { name: "Mahogany plank", tags: ["construction"] },
      { name: "Plank", tags: ["construction"] },
      { name: "Steel bar", tags: ["construction", "smithing"] },
      { name: "Bolt of cloth", tags: ["construction"] },
      { name: "Limestone brick", tags: ["construction"] },
      { name: "Gold leaf", tags: ["construction"] },
      { name: "Marble block", tags: ["construction"] },
      { name: "Magic stone", tags: ["construction"] },
      { name: "Mahogany hull parts", tags: ["construction"] },
      { name: "Mahogany repair kit", tags: ["construction"] },
      { name: "Mithril nails", tags: ["construction"] },
      { name: "Swamp paste", tags: ["construction"] },
    ],
  },
  {
    id: "prayer",
    label: "Prayer",
    kind: "skilling",
    note: "Bones (gilded/chaos/shards), offering spells, ensouled heads",
    items: [
      { name: "Big bones", tags: ["prayer"] },
      { name: "Dragon bones", tags: ["prayer"] },
      { name: "Wyrm bones", tags: ["prayer"] },
      { name: "Lava dragon bones", tags: ["prayer"] },
      { name: "Dagannoth bones", tags: ["prayer"] },
      { name: "Hydra bones", tags: ["prayer"] },
      { name: "Superior dragon bones", tags: ["prayer"] },
      { name: "Fiendish ashes", tags: ["prayer"] },
      { name: "Vile ashes", tags: ["prayer"] },
      { name: "Malicious ashes", tags: ["prayer"] },
      { name: "Abyssal ashes", tags: ["prayer"] },
      { name: "Infernal ashes", tags: ["prayer"] },
      { name: "Ensouled goblin head", tags: ["prayer"] },
      { name: "Ensouled monkey head", tags: ["prayer"] },
      { name: "Ensouled imp head", tags: ["prayer"] },
      { name: "Ensouled minotaur head", tags: ["prayer"] },
      { name: "Ensouled scorpion head", tags: ["prayer"] },
      { name: "Ensouled bear head", tags: ["prayer"] },
      { name: "Ensouled unicorn head", tags: ["prayer"] },
      { name: "Ensouled dog head", tags: ["prayer"] },
      { name: "Ensouled chaos druid head", tags: ["prayer"] },
      { name: "Ensouled giant head", tags: ["prayer"] },
      { name: "Ensouled ogre head", tags: ["prayer"] },
      { name: "Ensouled elf head", tags: ["prayer"] },
      { name: "Ensouled troll head", tags: ["prayer"] },
      { name: "Ensouled horror head", tags: ["prayer"] },
      { name: "Ensouled kalphite head", tags: ["prayer"] },
      { name: "Ensouled dagannoth head", tags: ["prayer"] },
      { name: "Ensouled bloodveld head", tags: ["prayer"] },
      { name: "Ensouled tzhaar head", tags: ["prayer"] },
      { name: "Ensouled demon head", tags: ["prayer"] },
      { name: "Ensouled hellhound head", tags: ["prayer"] },
      { name: "Ensouled aviansie head", tags: ["prayer"] },
      { name: "Ensouled abyssal head", tags: ["prayer"] },
      { name: "Ensouled dragon head", tags: ["prayer"] },
    ],
  },
  {
    id: "crafting",
    label: "Crafting",
    kind: "skilling",
    note: "Glassblowing, d'hide bodies, battlestaves and amethyst tips",
    items: [
      { name: "Molten glass", tags: ["crafting"] },
      { name: "Giant seaweed", tags: ["crafting"] },
      { name: "Bucket of sand", tags: ["crafting"] },
      { name: "Green dragon leather", tags: ["crafting"] },
      { name: "Blue dragon leather", tags: ["crafting"] },
      { name: "Red dragon leather", tags: ["crafting"] },
      { name: "Black dragon leather", tags: ["crafting"] },
      { name: "Battlestaff", tags: ["crafting"] },
      { name: "Air orb", tags: ["crafting"] },
      { name: "Water orb", tags: ["crafting"] },
      { name: "Uncut diamond", tags: ["crafting"] },
      { name: "Gold bar", tags: ["crafting", "smithing"] },
      { name: "Amethyst", tags: ["crafting", "mining"] },
      { name: "Amethyst bolt tips", tags: ["crafting", "fletching"] },
      { name: "Amethyst arrowtips", tags: ["crafting", "fletching"] },
      { name: "Amethyst javelin tips", tags: ["crafting", "fletching"] },
      { name: "Amethyst dart tip", tags: ["crafting", "fletching"] },
    ],
  },
  {
    id: "smithing",
    label: "Smithing & Mining",
    kind: "skilling",
    note: "Blast furnace, dart tips, nails, cannonballs, armour",
    items: [
      { name: "Copper ore", tags: ["smithing", "mining"] },
      { name: "Tin ore", tags: ["smithing", "mining"] },
      { name: "Iron ore", tags: ["smithing", "mining"] },
      { name: "Coal", tags: ["smithing", "mining"] },
      { name: "Gold ore", tags: ["smithing", "mining"] },
      { name: "Mithril ore", tags: ["smithing", "mining"] },
      { name: "Adamantite ore", tags: ["smithing", "mining"] },
      { name: "Runite ore", tags: ["smithing", "mining"] },
      { name: "Bronze bar", tags: ["smithing"] },
      { name: "Iron bar", tags: ["smithing"] },
      { name: "Steel bar", tags: ["smithing", "construction"] },
      { name: "Gold bar", tags: ["smithing"] },
      { name: "Mithril bar", tags: ["smithing"] },
      { name: "Adamantite bar", tags: ["smithing"] },
      { name: "Runite bar", tags: ["smithing"] },
      { name: "Bronze dart tip", tags: ["smithing", "fletching"] },
      { name: "Iron dart tip", tags: ["smithing", "fletching"] },
      { name: "Steel dart tip", tags: ["smithing", "fletching"] },
      { name: "Mithril dart tip", tags: ["smithing", "fletching"] },
      { name: "Adamant dart tip", tags: ["smithing", "fletching"] },
      { name: "Rune dart tip", tags: ["smithing", "fletching"] },
      { name: "Bronze nails", tags: ["smithing", "construction"] },
      { name: "Iron nails", tags: ["smithing", "construction"] },
      { name: "Steel nails", tags: ["smithing", "construction"] },
      { name: "Mithril nails", tags: ["smithing", "construction"] },
      { name: "Adamantite nails", tags: ["smithing", "construction"] },
      { name: "Rune nails", tags: ["smithing", "construction"] },
      { name: "Steel cannonball", tags: ["smithing"] },
      { name: "Iron platebody", tags: ["smithing"] },
      { name: "Steel platebody", tags: ["smithing"] },
      { name: "Mithril platebody", tags: ["smithing"] },
      { name: "Adamant platebody", tags: ["smithing"] },
      { name: "Rune platebody", tags: ["smithing"] },
      { name: "Rune 2h sword", tags: ["smithing"] },
      { name: "Rune platelegs", tags: ["smithing"] },
      { name: "Rune plateskirt", tags: ["smithing"] },
      { name: "Rune kiteshield", tags: ["smithing"] },
      { name: "Rune battleaxe", tags: ["smithing"] },
      { name: "Rune warhammer", tags: ["smithing"] },
    ],
  },
  {
    id: "magic-skilling",
    label: "Magic & Runecraft",
    kind: "skilling",
    note: "Alching, superheat and rune inputs",
    items: [
      { name: "Nature rune", tags: ["magic", "runecraft"] },
      { name: "Law rune", tags: ["magic", "runecraft"] },
      { name: "Death rune", tags: ["magic", "runecraft"] },
      { name: "Blood rune", tags: ["magic", "runecraft"] },
      { name: "Cosmic rune", tags: ["magic", "runecraft"] },
      { name: "Astral rune", tags: ["magic", "runecraft"] },
      { name: "Fire rune", tags: ["magic", "runecraft"] },
      { name: "Chaos rune", tags: ["magic", "runecraft"] },
      { name: "Pure essence", tags: ["runecraft", "mining"] },
      { name: "Rune dart", tags: ["fletching", "magic"] },
      { name: "Yew longbow", tags: ["fletching"] },
      { name: "Magic longbow", tags: ["fletching"] },
    ],
  },
  {
    id: "farming",
    label: "Farming & Herbs",
    kind: "skilling",
    note: "Tree runs and herb patch seeds",
    items: [
      { name: "Magic seed", tags: ["farming"] },
      { name: "Palm tree seed", tags: ["farming"] },
      { name: "Yew seed", tags: ["farming"] },
      { name: "Redwood tree seed", tags: ["farming"] },
      { name: "Papaya tree seed", tags: ["farming"] },
      { name: "Ranarr seed", tags: ["farming", "herblore"] },
      { name: "Snapdragon seed", tags: ["farming", "herblore"] },
      { name: "Torstol seed", tags: ["farming", "herblore"] },
      { name: "Ultracompost", tags: ["farming"] },
      { name: "Bottomless compost bucket", tags: ["farming"] },
    ],
  },
  {
    id: "misc-skilling",
    label: "Fletching, Cooking & Agility",
    kind: "skilling",
    note: "Darts, karambwans and stamina supplies",
    items: [
      { name: "Adamant dart tip", tags: ["fletching"] },
      { name: "Rune dart tip", tags: ["fletching"] },
      { name: "Feather", tags: ["fletching"] },
      { name: "Yew logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Magic logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Teak logs", tags: ["construction", "firemaking", "woodcutting"] },
      { name: "Mahogany logs", tags: ["construction", "firemaking", "woodcutting"] },
      { name: "Raw karambwan", tags: ["cooking"] },
      { name: "Raw shark", tags: ["cooking"] },
      { name: "Raw anglerfish", tags: ["cooking"] },
    ],
  },
];

export const GEAR_COMBAT_FILTERS = [
  { key: "melee", label: "Melee", icon: "Sword" },
  { key: "range", label: "Range", icon: "Target" },
  { key: "magic", label: "Magic", icon: "Sparkles" },
] as const;

export const GEAR_TIER_FILTERS = [
  { key: "early", label: "Early" },
  { key: "mid", label: "Mid" },
  { key: "late", label: "Late" },
  { key: "end", label: "End" },
] as const;

export const GEAR_SLOT_FILTERS = [
  { key: "head", label: "Head", wikiIcon: "Head_slot.png", row: 1, col: 2 },
  { key: "cape", label: "Cape", wikiIcon: "Cape_slot.png", row: 2, col: 1 },
  { key: "neck", label: "Neck", wikiIcon: "Neck_slot.png", row: 2, col: 2 },
  { key: "ammo", label: "Ammo", wikiIcon: "Ammo_slot.png", row: 2, col: 3 },
  { key: "weapon", label: "Weapon", wikiIcon: "Weapon_slot.png", row: 3, col: 1 },
  { key: "chest", label: "Body", wikiIcon: "Body_slot.png", row: 3, col: 2 },
  { key: "shield", label: "Shield", wikiIcon: "Shield_slot.png", row: 3, col: 3 },
  { key: "legs", label: "Legs", wikiIcon: "Legs_slot.png", row: 4, col: 2 },
  { key: "hands", label: "Hands", wikiIcon: "Hands_slot.png", row: 5, col: 1 },
  { key: "feet", label: "Feet", wikiIcon: "Feet_slot.png", row: 5, col: 2 },
  { key: "ring", label: "Ring", wikiIcon: "Ring_slot.png", row: 5, col: 3 },
] as const;

export const SKILLING_FILTERS = [
  { key: "herblore", label: "Herblore", wikiIcon: "Herblore_icon.png" },
  { key: "construction", label: "Construction", wikiIcon: "Construction_icon.png" },
  { key: "prayer", label: "Prayer", wikiIcon: "Prayer_icon.png" },
  { key: "crafting", label: "Crafting", wikiIcon: "Crafting_icon.png" },
  { key: "smithing", label: "Smithing", wikiIcon: "Smithing_icon.png" },
  { key: "magic", label: "Magic", wikiIcon: "Magic_icon.png" },
  { key: "runecraft", label: "Runecraft", wikiIcon: "Runecraft_icon.png" },
  { key: "farming", label: "Farming", wikiIcon: "Farming_icon.png" },
  { key: "fletching", label: "Fletching", wikiIcon: "Fletching_icon.png" },
  { key: "cooking", label: "Cooking", wikiIcon: "Cooking_icon.png" },
  { key: "agility", label: "Agility", wikiIcon: "Agility_icon.png" },
] as const;

/** Sub-filters on the Supplies tab. Keys match catalog tags. */
export const SUPPLIES_FILTERS = [
  { key: "ammo", label: "Ammunition", wikiIcon: "Ammo_slot.png" },
  { key: "food", label: "Food", wikiIcon: "Shark.png" },
  { key: "potion", label: "Potions", wikiIcon: "Prayer_potion(4).png" },
] as const;
