export type CatalogGroup = {
  id: string;
  label: string;
  kind: "gear" | "skilling";
  /** For skilling: the wiki training method this item belongs to. */
  note: string;
  items: string[];
};

/**
 * Curated catalog: gear people actually buy, and skilling supplies for the
 * popular / efficient methods from the OSRS Wiki training guides.
 * Items are referenced by exact wiki name and resolved to IDs at runtime.
 */
export const CATALOG: CatalogGroup[] = [
  {
    id: "melee",
    label: "Melee gear",
    kind: "gear",
    note: "Core melee upgrades",
    items: [
      "Abyssal whip",
      "Kraken tentacle",
      "Dragon scimitar",
      "Bandos chestplate",
      "Bandos tassets",
      "Amulet of torture",
      "Amulet of fury",
      "Primordial boots",
      "Dragon claws",
      "Ghrazi rapier",
      "Scythe of vitur (uncharged)",
      "Inquisitor's mace",
      "Justiciar faceguard",
      "Torva full helm",
      "Torva platelegs",
    ],
  },
  {
    id: "ranged",
    label: "Ranged gear",
    kind: "gear",
    note: "Core ranged upgrades",
    items: [
      "Toxic blowpipe (empty)",
      "Armadyl crossbow",
      "Dragon crossbow",
      "Twisted bow",
      "Bow of faerdhinen (inactive)",
      "Armadyl chestplate",
      "Armadyl chainskirt",
      "Armadyl helmet",
      "Necklace of anguish",
      "Pegasian boots",
      "Zaryte vambraces",
      "Masori body (f)",
      "Masori chaps (f)",
      "Dragon arrow",
      "Amethyst arrow",
      "Ruby dragon bolts (e)",
      "Diamond dragon bolts (e)",
    ],
  },
  {
    id: "magic",
    label: "Magic gear",
    kind: "gear",
    note: "Core magic upgrades",
    items: [
      "Trident of the seas (full)",
      "Uncharged toxic trident",
      "Ancestral hat",
      "Ancestral robe top",
      "Ancestral robe bottom",
      "Occult necklace",
      "Eternal boots",
      "Tormented bracelet",
      "Kodai wand",
      "Ahrim's robetop",
      "Ahrim's robeskirt",
      "Mystic robe top (dark)",
      "Tumeken's shadow (uncharged)",
    ],
  },
  {
    id: "utility",
    label: "Utility & supplies",
    kind: "gear",
    note: "Consumables and everyday kit",
    items: [
      "Saradomin brew(4)",
      "Super restore(4)",
      "Prayer potion(4)",
      "Ranging potion(4)",
      "Super combat potion(4)",
      "Divine super combat potion(4)",
      "Stamina potion(4)",
      "Anglerfish",
      "Shark",
      "Manta ray",
      "Blighted karambwan",
      "Dragon boots",
      "Amulet of glory(6)",
    ],
  },
  {
    id: "herblore",
    label: "Herblore",
    kind: "skilling",
    note: "Wiki-recommended potion training (unf + secondary)",
    items: [
      "Grimy ranarr weed",
      "Ranarr weed",
      "Snapdragon",
      "Toadflax",
      "Torstol",
      "Kwuarm",
      "Cadantine",
      "Lantadyme",
      "Dwarf weed",
      "Snape grass",
      "Crushed nest",
      "Wine of zamorak",
      "Vial of water",
      "Amylase crystal",
    ],
  },
  {
    id: "construction",
    label: "Construction",
    kind: "skilling",
    note: "Oak larders → mahogany tables → myth capes",
    items: [
      "Oak plank",
      "Teak plank",
      "Mahogany plank",
      "Plank",
      "Steel bar",
      "Bolt of cloth",
      "Limestone brick",
      "Gold leaf",
      "Marble block",
      "Magic stone",
    ],
  },
  {
    id: "prayer",
    label: "Prayer",
    kind: "skilling",
    note: "Ensouled heads & bone burying/offering",
    items: [
      "Dragon bones",
      "Superior dragon bones",
      "Wyrm bones",
      "Dagannoth bones",
      "Lava dragon bones",
      "Ensouled dragon head",
      "Ensouled abyssal head",
      "Ensouled bloodveld head",
    ],
  },
  {
    id: "crafting",
    label: "Crafting",
    kind: "skilling",
    note: "Glassblowing, d'hide bodies and battlestaves",
    items: [
      "Molten glass",
      "Giant seaweed",
      "Bucket of sand",
      "Green dragon leather",
      "Blue dragon leather",
      "Red dragon leather",
      "Black dragon leather",
      "Battlestaff",
      "Air orb",
      "Water orb",
      "Uncut diamond",
      "Gold bar",
    ],
  },
  {
    id: "smithing",
    label: "Smithing & Mining",
    kind: "skilling",
    note: "Blast furnace bars and ore inputs",
    items: [
      "Iron ore",
      "Coal",
      "Mithril ore",
      "Adamantite ore",
      "Runite ore",
      "Gold ore",
      "Mithril bar",
      "Adamantite bar",
      "Runite bar",
      "Steel bar",
    ],
  },
  {
    id: "magic-skilling",
    label: "Magic & Runecraft",
    kind: "skilling",
    note: "Alching, superheat and rune inputs",
    items: [
      "Nature rune",
      "Law rune",
      "Death rune",
      "Blood rune",
      "Cosmic rune",
      "Astral rune",
      "Fire rune",
      "Chaos rune",
      "Pure essence",
      "Rune dart",
      "Yew longbow",
      "Magic longbow",
    ],
  },
  {
    id: "farming",
    label: "Farming & Herbs",
    kind: "skilling",
    note: "Tree runs and herb patch seeds",
    items: [
      "Magic seed",
      "Palm tree seed",
      "Yew seed",
      "Redwood tree seed",
      "Papaya tree seed",
      "Ranarr seed",
      "Snapdragon seed",
      "Torstol seed",
      "Ultracompost",
      "Bottomless compost bucket",
    ],
  },
  {
    id: "misc-skilling",
    label: "Fletching, Cooking & Agility",
    kind: "skilling",
    note: "Darts, karambwans and stamina supplies",
    items: [
      "Adamant dart tip",
      "Rune dart tip",
      "Feather",
      "Yew logs",
      "Magic logs",
      "Teak logs",
      "Mahogany logs",
      "Raw karambwan",
      "Raw shark",
      "Raw anglerfish",
    ],
  },
];
