export type CatalogItem = {
  name: string;
  /** Filter tags for subset navigation. */
  tags: string[];
};

export type CatalogGroup = {
  id: string;
  label: string;
  kind: "gear" | "skilling";
  /** For skilling: the wiki training method this item belongs to. */
  note: string;
  items: CatalogItem[];
};

/**
 * Curated catalog: gear people actually buy, and skilling supplies for the
 * popular / efficient methods from the OSRS Wiki training guides.
 * Items are referenced by exact wiki name and resolved to IDs at runtime.
 */
export const CATALOG: CatalogGroup[] = [
  {
    id: "melee",
    label: "Melee gear",
    kind: "gear",
    note: "Core melee upgrades",
    items: [
      { name: "Abyssal whip", tags: ["melee", "weapon", "one-handed"] },
      { name: "Kraken tentacle", tags: ["melee", "weapon", "one-handed"] },
      { name: "Dragon scimitar", tags: ["melee", "weapon", "one-handed"] },
      { name: "Bandos chestplate", tags: ["melee", "chest"] },
      { name: "Bandos tassets", tags: ["melee", "legs"] },
      { name: "Amulet of torture", tags: ["melee", "neck"] },
      { name: "Amulet of fury", tags: ["melee", "neck"] },
      { name: "Primordial boots", tags: ["melee", "feet"] },
      { name: "Dragon claws", tags: ["melee", "weapon", "two-handed"] },
      { name: "Ghrazi rapier", tags: ["melee", "weapon", "one-handed"] },
      { name: "Scythe of vitur (uncharged)", tags: ["melee", "weapon", "two-handed"] },
      { name: "Inquisitor's mace", tags: ["melee", "weapon", "one-handed"] },
      { name: "Justiciar faceguard", tags: ["melee", "head"] },
      { name: "Torva full helm", tags: ["melee", "head"] },
      { name: "Torva platelegs", tags: ["melee", "legs"] },
    ],
  },
  {
    id: "ranged",
    label: "Ranged gear",
    kind: "gear",
    note: "Core ranged upgrades",
    items: [
      { name: "Toxic blowpipe (empty)", tags: ["range", "weapon", "two-handed"] },
      { name: "Armadyl crossbow", tags: ["range", "weapon", "one-handed"] },
      { name: "Dragon crossbow", tags: ["range", "weapon", "one-handed"] },
      { name: "Twisted bow", tags: ["range", "weapon", "two-handed"] },
      { name: "Bow of faerdhinen (inactive)", tags: ["range", "weapon", "two-handed"] },
      { name: "Armadyl chestplate", tags: ["range", "chest"] },
      { name: "Armadyl chainskirt", tags: ["range", "legs"] },
      { name: "Armadyl helmet", tags: ["range", "head"] },
      { name: "Necklace of anguish", tags: ["range", "neck"] },
      { name: "Pegasian boots", tags: ["range", "feet"] },
      { name: "Zaryte vambraces", tags: ["range", "hands"] },
      { name: "Masori body (f)", tags: ["range", "chest"] },
      { name: "Masori chaps (f)", tags: ["range", "legs"] },
      { name: "Dragon arrow", tags: ["range", "ammo"] },
      { name: "Amethyst arrow", tags: ["range", "ammo"] },
      { name: "Ruby dragon bolts (e)", tags: ["range", "ammo"] },
      { name: "Diamond dragon bolts (e)", tags: ["range", "ammo"] },
    ],
  },
  {
    id: "magic",
    label: "Magic gear",
    kind: "gear",
    note: "Core magic upgrades",
    items: [
      { name: "Trident of the seas (full)", tags: ["magic", "weapon", "one-handed"] },
      { name: "Uncharged toxic trident", tags: ["magic", "weapon", "one-handed"] },
      { name: "Ancestral hat", tags: ["magic", "head"] },
      { name: "Ancestral robe top", tags: ["magic", "chest"] },
      { name: "Ancestral robe bottom", tags: ["magic", "legs"] },
      { name: "Occult necklace", tags: ["magic", "neck"] },
      { name: "Eternal boots", tags: ["magic", "feet"] },
      { name: "Tormented bracelet", tags: ["magic", "hands"] },
      { name: "Kodai wand", tags: ["magic", "weapon", "one-handed"] },
      { name: "Ahrim's robetop", tags: ["magic", "chest"] },
      { name: "Ahrim's robeskirt", tags: ["magic", "legs"] },
      { name: "Mystic robe top (dark)", tags: ["magic", "chest"] },
      { name: "Tumeken's shadow (uncharged)", tags: ["magic", "weapon", "two-handed"] },
    ],
  },
  {
    id: "utility",
    label: "Utility & supplies",
    kind: "gear",
    note: "Consumables and everyday kit",
    items: [
      { name: "Saradomin brew(4)", tags: ["supplies", "potion"] },
      { name: "Super restore(4)", tags: ["supplies", "potion"] },
      { name: "Prayer potion(4)", tags: ["supplies", "potion"] },
      { name: "Ranging potion(4)", tags: ["supplies", "potion"] },
      { name: "Super combat potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine super combat potion(4)", tags: ["supplies", "potion"] },
      { name: "Stamina potion(4)", tags: ["supplies", "potion"] },
      { name: "Anglerfish", tags: ["supplies", "food"] },
      { name: "Shark", tags: ["supplies", "food"] },
      { name: "Manta ray", tags: ["supplies", "food"] },
      { name: "Blighted karambwan", tags: ["supplies", "food"] },
      { name: "Dragon boots", tags: ["supplies", "feet"] },
      { name: "Amulet of glory(6)", tags: ["supplies", "neck"] },
    ],
  },
  {
    id: "herblore",
    label: "Herblore",
    kind: "skilling",
    note: "Wiki-recommended potion training (unf + secondary)",
    items: [
      { name: "Grimy ranarr weed", tags: ["herblore"] },
      { name: "Ranarr weed", tags: ["herblore"] },
      { name: "Snapdragon", tags: ["herblore"] },
      { name: "Toadflax", tags: ["herblore"] },
      { name: "Torstol", tags: ["herblore"] },
      { name: "Kwuarm", tags: ["herblore"] },
      { name: "Cadantine", tags: ["herblore"] },
      { name: "Lantadyme", tags: ["herblore"] },
      { name: "Dwarf weed", tags: ["herblore"] },
      { name: "Snape grass", tags: ["herblore"] },
      { name: "Crushed nest", tags: ["herblore"] },
      { name: "Wine of zamorak", tags: ["herblore"] },
      { name: "Vial of water", tags: ["herblore"] },
      { name: "Amylase crystal", tags: ["herblore"] },
    ],
  },
  {
    id: "construction",
    label: "Construction",
    kind: "skilling",
    note: "Oak larders → mahogany tables → myth capes",
    items: [
      { name: "Oak plank", tags: ["construction"] },
      { name: "Teak plank", tags: ["construction"] },
      { name: "Mahogany plank", tags: ["construction"] },
      { name: "Plank", tags: ["construction"] },
      { name: "Steel bar", tags: ["construction", "smithing"] },
      { name: "Bolt of cloth", tags: ["construction"] },
      { name: "Limestone brick", tags: ["construction"] },
      { name: "Gold leaf", tags: ["construction"] },
      { name: "Marble block", tags: ["construction"] },
      { name: "Magic stone", tags: ["construction"] },
    ],
  },
  {
    id: "prayer",
    label: "Prayer",
    kind: "skilling",
    note: "Ensouled heads & bone burying/offering",
    items: [
      { name: "Dragon bones", tags: ["prayer"] },
      { name: "Superior dragon bones", tags: ["prayer"] },
      { name: "Wyrm bones", tags: ["prayer"] },
      { name: "Dagannoth bones", tags: ["prayer"] },
      { name: "Lava dragon bones", tags: ["prayer"] },
      { name: "Ensouled dragon head", tags: ["prayer"] },
      { name: "Ensouled abyssal head", tags: ["prayer"] },
      { name: "Ensouled bloodveld head", tags: ["prayer"] },
    ],
  },
  {
    id: "crafting",
    label: "Crafting",
    kind: "skilling",
    note: "Glassblowing, d'hide bodies and battlestaves",
    items: [
      { name: "Molten glass", tags: ["crafting"] },
      { name: "Giant seaweed", tags: ["crafting"] },
      { name: "Bucket of sand", tags: ["crafting"] },
      { name: "Green dragon leather", tags: ["crafting"] },
      { name: "Blue dragon leather", tags: ["crafting"] },
      { name: "Red dragon leather", tags: ["crafting"] },
      { name: "Black dragon leather", tags: ["crafting"] },
      { name: "Battlestaff", tags: ["crafting"] },
      { name: "Air orb", tags: ["crafting"] },
      { name: "Water orb", tags: ["crafting"] },
      { name: "Uncut diamond", tags: ["crafting"] },
      { name: "Gold bar", tags: ["crafting", "smithing"] },
    ],
  },
  {
    id: "smithing",
    label: "Smithing & Mining",
    kind: "skilling",
    note: "Blast furnace bars and ore inputs",
    items: [
      { name: "Iron ore", tags: ["smithing", "mining"] },
      { name: "Coal", tags: ["smithing", "mining"] },
      { name: "Mithril ore", tags: ["smithing", "mining"] },
      { name: "Adamantite ore", tags: ["smithing", "mining"] },
      { name: "Runite ore", tags: ["smithing", "mining"] },
      { name: "Gold ore", tags: ["smithing", "mining"] },
      { name: "Mithril bar", tags: ["smithing"] },
      { name: "Adamantite bar", tags: ["smithing"] },
      { name: "Runite bar", tags: ["smithing"] },
      { name: "Steel bar", tags: ["smithing", "construction"] },
    ],
  },
  {
    id: "magic-skilling",
    label: "Magic & Runecraft",
    kind: "skilling",
    note: "Alching, superheat and rune inputs",
    items: [
      { name: "Nature rune", tags: ["magic", "runecraft"] },
      { name: "Law rune", tags: ["magic", "runecraft"] },
      { name: "Death rune", tags: ["magic", "runecraft"] },
      { name: "Blood rune", tags: ["magic", "runecraft"] },
      { name: "Cosmic rune", tags: ["magic", "runecraft"] },
      { name: "Astral rune", tags: ["magic", "runecraft"] },
      { name: "Fire rune", tags: ["magic", "runecraft"] },
      { name: "Chaos rune", tags: ["magic", "runecraft"] },
      { name: "Pure essence", tags: ["runecraft", "mining"] },
      { name: "Rune dart", tags: ["fletching", "magic"] },
      { name: "Yew longbow", tags: ["fletching"] },
      { name: "Magic longbow", tags: ["fletching"] },
    ],
  },
  {
    id: "farming",
    label: "Farming & Herbs",
    kind: "skilling",
    note: "Tree runs and herb patch seeds",
    items: [
      { name: "Magic seed", tags: ["farming"] },
      { name: "Palm tree seed", tags: ["farming"] },
      { name: "Yew seed", tags: ["farming"] },
      { name: "Redwood tree seed", tags: ["farming"] },
      { name: "Papaya tree seed", tags: ["farming"] },
      { name: "Ranarr seed", tags: ["farming", "herblore"] },
      { name: "Snapdragon seed", tags: ["farming", "herblore"] },
      { name: "Torstol seed", tags: ["farming", "herblore"] },
      { name: "Ultracompost", tags: ["farming"] },
      { name: "Bottomless compost bucket", tags: ["farming"] },
    ],
  },
  {
    id: "misc-skilling",
    label: "Fletching, Cooking & Agility",
    kind: "skilling",
    note: "Darts, karambwans and stamina supplies",
    items: [
      { name: "Adamant dart tip", tags: ["fletching"] },
      { name: "Rune dart tip", tags: ["fletching"] },
      { name: "Feather", tags: ["fletching"] },
      { name: "Yew logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Magic logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Teak logs", tags: ["construction", "firemaking", "woodcutting"] },
      { name: "Mahogany logs", tags: ["construction", "firemaking", "woodcutting"] },
      { name: "Raw karambwan", tags: ["cooking"] },
      { name: "Raw shark", tags: ["cooking"] },
      { name: "Raw anglerfish", tags: ["cooking"] },
    ],
  },
];

export const GEAR_COMBAT_FILTERS = [
  { key: "melee", label: "Melee", icon: "Sword" },
  { key: "range", label: "Range", icon: "Target" },
  { key: "magic", label: "Magic", icon: "Sparkles" },
  { key: "supplies", label: "Supplies", icon: "Package" },
] as const;

export const GEAR_SLOT_FILTERS = [
  { key: "head", label: "Head", icon: "HardHat" },
  { key: "chest", label: "Chest", icon: "Shirt" },
  { key: "legs", label: "Legs", icon: "Circle" },
  { key: "one-handed", label: "One-handed", icon: "Hand" },
  { key: "two-handed", label: "Two-handed", icon: "Grip" },
  { key: "ammo", label: "Ammo", icon: "CircleDot" },
  { key: "feet", label: "Feet", icon: "Footprints" },
  { key: "neck", label: "Neck", icon: "Gem" },
  { key: "hands", label: "Hands", icon: "Hand" },
  { key: "weapon", label: "Weapon", icon: "Sword" },
  { key: "shield", label: "Shield", icon: "Shield" },
  { key: "food", label: "Food", icon: "UtensilsCrossed" },
  { key: "potion", label: "Potion", icon: "FlaskConical" },
] as const;

/** Wiki skill icon filenames from https://oldschool.runescape.wiki/w/Category:Skill_icons */
export const SKILLING_FILTERS = [
  { key: "herblore", label: "Herblore", wikiIcon: "Herblore_icon.png" },
  { key: "construction", label: "Construction", wikiIcon: "Construction_icon.png" },
  { key: "prayer", label: "Prayer", wikiIcon: "Prayer_icon.png" },
  { key: "crafting", label: "Crafting", wikiIcon: "Crafting_icon.png" },
  { key: "smithing", label: "Smithing", wikiIcon: "Smithing_icon.png" },
  { key: "magic", label: "Magic", wikiIcon: "Magic_icon.png" },
  { key: "runecraft", label: "Runecraft", wikiIcon: "Runecraft_icon.png" },
  { key: "farming", label: "Farming", wikiIcon: "Farming_icon.png" },
  { key: "fletching", label: "Fletching", wikiIcon: "Fletching_icon.png" },
  { key: "cooking", label: "Cooking", wikiIcon: "Cooking_icon.png" },
  { key: "agility", label: "Agility", wikiIcon: "Agility_icon.png" },
] as const;
