/** In-game Skills tab order: 3 columns, 8 rows. */
export const SKILLS_PANEL = [
  { key: "attack", label: "Attack", wikiIcon: "Attack_icon.png" },
  { key: "hitpoints", label: "Hitpoints", wikiIcon: "Hitpoints_icon.png" },
  { key: "mining", label: "Mining", wikiIcon: "Mining_icon.png" },
  { key: "strength", label: "Strength", wikiIcon: "Strength_icon.png" },
  { key: "agility", label: "Agility", wikiIcon: "Agility_icon.png" },
  { key: "smithing", label: "Smithing", wikiIcon: "Smithing_icon.png" },
  { key: "defence", label: "Defence", wikiIcon: "Defence_icon.png" },
  { key: "herblore", label: "Herblore", wikiIcon: "Herblore_icon.png" },
  { key: "fishing", label: "Fishing", wikiIcon: "Fishing_icon.png" },
  { key: "ranged", label: "Ranged", wikiIcon: "Ranged_icon.png" },
  { key: "thieving", label: "Thieving", wikiIcon: "Thieving_icon.png" },
  { key: "cooking", label: "Cooking", wikiIcon: "Cooking_icon.png" },
  { key: "prayer", label: "Prayer", wikiIcon: "Prayer_icon.png" },
  { key: "crafting", label: "Crafting", wikiIcon: "Crafting_icon.png" },
  { key: "firemaking", label: "Firemaking", wikiIcon: "Firemaking_icon.png" },
  { key: "magic", label: "Magic", wikiIcon: "Magic_icon.png" },
  { key: "fletching", label: "Fletching", wikiIcon: "Fletching_icon.png" },
  { key: "woodcutting", label: "Woodcutting", wikiIcon: "Woodcutting_icon.png" },
  { key: "runecraft", label: "Runecraft", wikiIcon: "Runecraft_icon.png" },
  { key: "slayer", label: "Slayer", wikiIcon: "Slayer_icon.png" },
  { key: "farming", label: "Farming", wikiIcon: "Farming_icon.png" },
  { key: "construction", label: "Construction", wikiIcon: "Construction_icon.png" },
  { key: "hunter", label: "Hunter", wikiIcon: "Hunter_icon.png" },
  { key: "sailing", label: "Sailing", wikiIcon: "Sailing_icon.png" },
] as const;
